### ISSUE TITLE
[BUG]课程表显示

### ISSUE THREAD

**Issue by fakepheonix** [DanXi-Dev/DanXi#102]
课表内的毛概课显示为毛概b，从而不显示上课教室

安卓版1.2.6 build65
![Screenshot_20211025_175244_io github danxi_dev dan_xi](https://user-images.githubusercontent.com/67363181/138674830-db846efa-5d7a-4202-ac3b-749e8b0c83db.png)

**Comment by w568w** [comment]
应该已经处理好了，详见 Commit：https://github.com/DanXi-Dev/DanXi/commit/d32c3b17b7e68548a358aa762e729b297c032c80

如果后续还有问题，可以 Reopen 这个 Issue。
