### ISSUE TITLE
[Feature Request] 简繁转换

### ISSUE THREAD

**Issue by singularity-s0** [DanXi-Dev/DanXi#103]
**你的功能需求和某个bug有关吗？**
是，原反馈：
> 一般iOS只要把文字圈起来就可以一键繁转简，但旦夕好像没办法，我只能在备忘录上写好转成简体再贴到旦夕，对于港澳台同学而言有些不太方便，整体来说还是挺好用的。

**你想要什么样的功能？**
发帖编辑器（甚至渲染器？）增加简繁转换功能

**Comment by w568w** [comment]
没有人规定树洞必须使用简体发言啊？
