### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kotorikanbe** [DanXi-Dev/DanXi#123]
很多手机无法通过安装包更新，Googleplay更新正常。
adb强制安装同样失败，报错如下：
C: \Users\9999>adb install -r "D:\旦夕_1.3.1 (2).apk "
adb: failed to install D:\旦夕_1.3.1(2).apk: Failure[INSTALL PARSE FATLED_MANIFEST_MALFORIED: Failed parse during installPackageLI: /data/ app/vmd1410309462. tmp/base.apk (at Binary XML file line #64) : io.github.w568w.dan_xi MainActivity: Targeting S+ (version 31 and above)requires that an explicit value for android;exported be defined when intent filters are present]
新安装的软件或者清除数据过的软件无法登录，显示没有链接互联网。

**Comment by w568w** [comment]
我会尽快检查这个问题。

**Comment by kotorikanbe** [comment]
> 我会尽快检查这个问题。

目前经过我的尝试，发现安卓12的机型会有以上问题，目前我成功通过windows subsystem of android（基于android11）可以正常安装及登录。

**Comment by w568w** [comment]
> > 我会尽快检查这个问题。
> 
> 目前经过我的尝试，发现安卓12的机型会有以上问题，目前我成功通过windows subsystem of android（基于android11）可以正常安装及登录。

是 Android 12 的硬性要求导致。目前已经解决了该问题，稍后将会紧急更新新版本。
