### ISSUE TITLE
[BUG] 首页面图形错误

### ISSUE THREAD

**Issue by OwenLou** [DanXi-Dev/DanXi#124]
版本1.3.3build106，ios手机端和ipados端，进入首界面后，出现很长的灰色框。

手机端如下两图，分别是灰色框的顶部和底部
![5F8C086A-A126-424E-A6D9-25BD993CB82D](https://user-images.githubusercontent.com/53600622/150824120-10ea3f13-3e29-4fbd-8c05-f7e31fb0403f.png)
![55437EF0-E554-46B6-A56F-AAE5CCC5FCF2](https://user-images.githubusercontent.com/53600622/150824135-8151639b-4f3f-4836-a07f-3d92f3e09c05.png)

不知道是不是我个人设备的问题？

**Comment by OwenLou** [comment]
刚刚又尝试了一下修改首页面标签顺序，发现这段灰色是存在于“校车班次”上侧的。

**Comment by w568w** [comment]
Duplicate of **FDUHole Post #55695**.
> 我们查出了原因：信息办的校车信息录入错误，导致某班校车的起点是「邯郸」校区，终点是「8:00江湾」校区，开车时间是「空」。因而导致旦夕解析错误。

Duplicate of **Dev-Team Announcement 2022-01-24 11:38:07**.

> 开发组公告 2022-01-24 11:38:07
>
> 关于「校车查询」已知问题的公告
> 各位用户，大家好。
> 
> 我们注意到首页的「校车查询」功能出现了一些问题，可能导致此卡片及其后的页面内容均变成灰色长条。初步判断此问题由服务器端API变化所导致。我们将尽快跟进修复。
> 
> 在此期间，各位用户可以在右上角的「编辑」菜单内将「校车班次」卡片暂时移除。其余功能可正常使用。
> 
> 为您带来不便，我们深表歉意。感谢大家的谅解！
> 
> 

**Please check these announcement sources before you submitting issues.** 

Closed.
