### ISSUE TITLE
[Feature Request] 图片查看器界面直接切换上一张/下一张

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#127]
**你的功能需求和某个bug有关吗？**
`否`

**你想要什么样的功能？**
在看帖页面点击图片后，可以直接切换查看本贴的下一张/上一张图片。

考虑到`ImageViewerPage`的独立性，应当包装其界面控件，实现一个类似于`ImageListViewerPage`的页面。这个页面在打开时应当被提供**一个目前已加载部分帖子的图片列表**，用于在`PageView `中显示图片；同时被提供**一个回调**，用于在切换到最后一张图片时，加载下一页的图片列表或提示用户已无更多图片。

**Comment by singularity-s0** [comment]
考虑到我们使用的是`CachedNetworkImage`，实际上仅需传递图片链接列表即可
