### ISSUE TITLE
[Feature Request] 发布到 F-Droid

### ISSUE THREAD

**Issue by linsui** [DanXi-Dev/DanXi#129]
**你的功能需求和某个bug有关吗？**
`否`

**你想要什么样的功能？**
请问是否可以将应用发布到 F-Droid？

**Comment by w568w** [comment]
我们有这个计划。但 F-Droid Repository 要求使用*完全开源*的源代码仓库进行编译，这意味着我们不能使用私有代码（包括但不限于用于登录树洞、获取公告、显示 Google 广告的应用识别码和 API 密钥等）。

如果真的上架到 F-Droid，那里的旦夕副本可能将不会包含树洞等基础功能。

**Comment by linsui** [comment]
Google 广告 google_mobile_ads 这个库应该不是开源的，所以需要去掉。API 密钥需要包含在代码库里所以会比较麻烦。可以添加一个不包含私有代码的 flavor。需要任何 F-Droid 相关的帮助也可以直接在这里 @ 我。谢谢！

**Comment by w568w** [comment]
我们已经开始着手这项工作了。

FOSS 分支：https://github.com/DanXi-Dev/DanXi/tree/foss-build

**Comment by linsui** [comment]
谢谢！

**Comment by linsui** [comment]
已合并，感谢你的帮助和支持！大概会在两三天内进入存储库。F-Droid 的徽标

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/io.github.danxi_dev.dan_xi)

```
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/io.github.danxi_dev.dan_xi)
```
