### ISSUE TITLE
[BUG]研究生UIS登录密码错误

### ISSUE THREAD

**Issue by MooreQiu** [DanXi-Dev/DanXi#133]
研究生登录提示密码错误
更改密码之后依然错误

**Comment by w568w** [comment]
请提供你的旦夕版本号和详细的错误提示信息内容。

**Comment by MooreQiu** [comment]
> 请提供你的旦夕版本号和详细的错误提示信息内容。

ios应用商店下载， 错误信息是：登陆失败，未知错误

**Comment by singularity-s0** [comment]
哪里提示密码错误？

**Comment by w568w** [comment]
> 错误信息是：登陆失败，未知错误

见树洞 #57327：
> 经过调试，我们发现是信息办把登录所用的 API 也限制在内网访问了，导致旦夕尝试登录时，一直得到「网络维护中」，因而不能登录，提示未知错误。
>我们会继续寻找其他可用的 API。在此之前，敬请连接 https://stuvpn.fudan.edu.cn/ 登录。

另外，https://github.com/DanXi-Dev/DanXi/commit/fea0dba351e060af2183eec99b06233b6f219c05 已经修复这一问题。会在下一版本包含这个修复。
