### ISSUE TITLE
[BUG] Scrolling by apple pencil doesn't work well

### ISSUE THREAD

**Issue by nqhq-lou** [DanXi-Dev/DanXi#137]
用apple pencil在树洞区域翻页时，页面滚动延迟，见下

1. 点开一个树洞的帖子
2. 尝试用apple pencil滚动页面（pencil不断向一个方向滑动）
    2.1. 发现applepencil先留下一段笔迹，约1s后笔记消失，页面开始跟随笔滚动
3. 或许页面应该直接跟着笔滚动

系统为ipadOS15.2.1
danxi版本为1.3.5 build 151
下面是录屏视频
https://user-images.githubusercontent.com/53600622/154184768-d0714a04-887c-4395-b6d8-c9ff9639d97e.mp4

**Comment by singularity-s0** [comment]
可以复现，但初步判定为上游框架问题，我们未必能修复。

**Comment by w568w** [comment]
Upstream issue is here: https://github.com/flutter/flutter/issues/101016. We will keep an eye for a fix.

**Comment by yy1300326388** [comment]
I think the easiest and fastest way is to modify the source code by yourself, and follow this modification https://github.com/flutter/flutter/pull/101087

**Comment by w568w** [comment]
> I think the easiest and fastest way is to modify the source code by yourself, and follow this modification [flutter/flutter#101087](https://github.com/flutter/flutter/pull/101087)

Thanks for informing! We hope it will not be so long before the patch comes into beta or dev channel.

**Comment by w568w** [comment]
Upstream has fixed it in the most recent version of Flutter. Close it.
