### ISSUE TITLE
[BUG] 旦夕在浏览某些帖子时崩溃

### ISSUE THREAD

**Issue by KYLN24** [DanXi-Dev/DanXi#143]
**Describe the bug**
浏览 #22023 与 #8531 到较深处时，旦夕会崩溃

**To Reproduce**
1. 访问 #22023 或 #8531
2. 向下翻阅至较深层（可尝试快速翻动与慢速翻动）
3. 旦夕崩溃

**Expected behavior**
不崩溃

**Screenshots**
无

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.3.1
 - Version 1.3.6b155

**Additional context**
猜想会引起崩溃的洞具有深且多图的特征。

该 bug 由用户通过用户群反馈。

**Comment by w568w** [comment]
在目前版本中很难复现，暂时 Close，直到该问题可以复现且频繁出现，以至于影响用户体验。
