### ISSUE TITLE
[Feature Request] Move exams to "Agenda" page

### ISSUE THREAD

**Issue by singularity-s0** [DanXi-Dev/DanXi#145]
Exam schedule are displayed at the page where we acquire user's time table, thus they can be added to the user's timetable without the need to access exam schedule page in JWFW.

This also frees the exams and scores subpage so it can be dedicated to displaying user's score.

**Comment by singularity-s0** [comment]
Exams can be labeled with secondary color (e.g. red) for more prominent UI presence.

We should also consider supporting adding custom lessons or events to the agenda page. This further reinforces our app's role as a dedicated school helper app.

**Comment by w568w** [comment]
> Exam schedule are displayed at the page where we acquire user's time table, thus they can be added to the user's timetable without the need to access exam schedule page in JWFW.

A primary obstacle is that exams have inconsistent data representation with courses.

Exams in JWFW use *absolute* date strings (usually `2023-01-16`) and time strings (varied. They can be `~23:59`, `10:00~10:30`, `10:00~`, `<space>`, etc.) to inform the duration of an examination. But courses are timed by teaching weeks (e.g. `1,2,3,4,16`), days (e.g. `1` for Monday) and slots (e.g. `3,4,5`). They do not correspond to each other explicitly.

Even if we assume that a user specifies the right semester beginning date, it is still painful to parse those bad-formed handwritten datetimes into our course data structures.

> We should also consider supporting adding custom lessons or events to the agenda page. This further reinforces our app's role as a dedicated school helper app.

It has been implemented, see #174.
