### ISSUE TITLE
[Feature Request]检测更新的功能

### ISSUE THREAD

**Issue by LinqiY** [DanXi-Dev/DanXi#146]
**你的功能需求和某个bug有关吗？**
`[是/否]`否

**你想要什么样的功能？**
退出更新的公告之后找不到更新的界面，在之后的登陆中也不会出现。
我建议的解决方案：
1. 在“关于”中增加一个检查更新的按钮。
2. 每次打开应用后均检查更新，若出现更新版本，弹出提示。

**Comment by w568w** [comment]
> 每次打开应用后均检查更新，若出现更新版本，弹出提示。

1. 你所说的这个功能，早在 10 个版本前就实现了，具体见 https://github.com/DanXi-Dev/DanXi/commit/56d9845b4a1675ddf048c07e6c3cbba4c02c2e6f 。

> 在“关于”中增加一个检查更新的按钮。

2. Android 上：见 1；iOS 上：App Store 规范不允许这么做。
