### ISSUE TITLE
[Feature Request] 适配评教系统

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#148]
如题。在下一个新版本发布前，应当尽快完成评教系统前端的编写。

如果暂时未定评教功能的位置，我的建议是放在「树洞」-「评教」中。

**Comment by w568w** [comment]
如果没有其他意见，暂时使用网页版也是可行的选择。

**Comment by w568w** [comment]
> 如果没有其他意见，暂时使用网页版也是可行的选择。

等待 https://github.com/OpenTreeHole/curriculum-board-frontend-vue2/issues/15 实现后方可继续。

**Comment by singularity-s0** [comment]
已实现
