### ISSUE TITLE
[BUG] 收藏夹向下滑动出现卡顿

### ISSUE THREAD

**Issue by hmtbgc** [DanXi-Dev/DanXi#155]
**Describe the bug**
收藏夹点开以后，无法向下滑动，超过5个以上的收藏无法显示

**To Reproduce**
点开收藏，向下滑动，无法滑动

**Expected behavior**
可以滑动

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: EMUI11.0.0
 - Browser: 客户端
 - Version: 1.3.8 

**Additional context**
今天（04.29）发现的错误，也有可能是系统的问题

**Comment by hmtbgc** [comment]
更新：在ios系统上不存在该问题

**Comment by singularity-s0** [comment]
Should be fixed with the removal of slivers in 1cc62f20.
