### ISSUE TITLE
[Feature Request] 收藏夹里收藏内容的删除方式

### ISSUE THREAD

**Issue by hmtbgc** [DanXi-Dev/DanXi#156]
**你的功能需求和某个bug有关吗？**
`[否]`

**你想要什么样的功能？**
收藏夹删除收藏条目时能否使用滑动删除，即像QQ那样向右滑动即可删除，而不是点开收藏条目，再点击上方星星删除。

**Comment by singularity-s0** [comment]
Implemented in 7695b848
