### ISSUE TITLE
[BUG]Windows版本旦夕客户端按shift时崩溃

### ISSUE THREAD

**Issue by Moonlight-lzs** [DanXi-Dev/DanXi#157]
打开windows版本的旦夕后在任意位置按shift会导致软件崩溃，该bug已持续多个版本

复现方法：
打开windows版本的旦夕客户端，按下shift，软件就会崩溃，提示"A New Flutter Project.已停止工作"
![image](https://user-images.githubusercontent.com/75473260/165932497-3a072bae-d0aa-40f8-9d49-79324d4a20a8.png)

 - OS: Windows 10 21H2
 - Browser: Edge Dev
 - Version: Windows 10版，1.3.8 Build 170

**Comment by w568w** [comment]
很抱歉，过去一周的调试中，我们始终未复现该问题。请报告如下的额外信息：

1. 在所有输入法选择下，旦夕都会崩溃，还是仅仅在某个输入法下？
2. 使用[较早期的版本](https://github.com/DanXi-Dev/DanXi/releases?page=2)（尽管它们大多无法正常登录、使用）。按 Shift 仍有相同的问题吗？

**Comment by Moonlight-lzs** [comment]
> 很抱歉，过去一周的调试中，我们始终未复现该问题。请报告如下的额外信息：
> 
> 1. 在所有输入法选择下，旦夕都会崩溃，还是仅仅在某个输入法下？
> 2. 使用[较早期的版本](https://github.com/DanXi-Dev/DanXi/releases?page=2)（尽管它们大多无法正常登录、使用）。按 Shift 仍有相同的问题吗？

抱歉，经此提醒我意识到可能是我自己所用输入法的问题。使用win10自带英文键盘重复操作并没有发生此崩溃，同时经测试发现在较早期的版本下使用该输入法也存在同样的问题。

我所使用的输入法为小鹤音形，属于双拼音形输入法的一种。由于此输入法相当小众，同时我也无法判断该崩溃是由于输入法还是由于旦夕客户端，因此如果无法抽出精力修复此问题，请您自便，经贵团队提醒我今后使用时留心切换即可。

附输入法下载链接以便复现使用：[http://flypy.ysepan.com/](url)

**Comment by w568w** [comment]
经过排查，我们认为这似乎并非是旦夕客户端的问题。

你可以到小鹤音形的官方论坛提交错误报告：https://flypy.cc/forum.php?mod=forumdisplay&fid=2&filter=typeid&typeid=4

或者到我们所使用的框架的开源社区，Flutter，新增一个 issue：https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=
