### ISSUE TITLE
[BUG] 无法登陆树洞

### ISSUE THREAD

**Issue by Achuan-2** [DanXi-Dev/DanXi#166]
你好，我是研究生新生。第一次下载旦夕app
登陆树洞，冒出SocketException
想知道是什么缘故，该如何解决
![IMG_20220820_214843](https://user-images.githubusercontent.com/60436214/185749409-5b026d7a-d3c5-44ff-970b-2362e1a79021.jpg)

**Comment by w568w** [comment]
最近服务器似乎时常受到大陆网络审查的阻断。请多次重试，或使用网络代理登录。

*其他问题可参考：[旦夕 FAQ](https://danxi-dev.feishu.cn/wiki/wikcnrPPGDCiTODBYRkdwLlHH65)*

**Comment by Achuan-2** [comment]
好的，谢谢。
安装了Clash Android就可以了
