### ISSUE TITLE
[Feature Request] 评教系统

### ISSUE THREAD

**Issue by singularity-s0** [DanXi-Dev/DanXi#18]
**你的功能需求和某个bug有关吗？**
否

**你想要什么样的功能？**
可以对课程进行评价，包括定性评价（推荐/不推荐；给分好/不好；能学到东西/不能学到；有趣/无趣等）及理由，以帮助同学策划选课。

**Comment by w568w** [comment]
新树洞的分区已经可以实现评教的功能了。
