### ISSUE TITLE
UIS文案改动

### ISSUE THREAD

**Issue by fsy2001** [DanXi-Dev/DanXi#181]
**你的功能需求和某个bug有关吗？**
否

**你想要什么样的功能？**

目前账户体系较为混乱，且UIS这一文案的表述不够清晰。需要将复旦账户与旦夕账户在UI上分开展示，并选择合适的文案。

**Comment by w568w** [comment]
具体讨论一下改动位置？我目前想到的有：

1. 将 UIS 和旦夕账户分开显示（**目前正是分开显示的，我认为无需修改**）
2. 将「UIS」文案全部改为「统一身份认证」
