### ISSUE TITLE
[BUG] 完成树洞登录后，回到树洞页面时应用不响应触摸

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#183]
**Describe the bug**
完成树洞登录后，回到树洞页面时应用不响应触摸。

**To Reproduce**
1. 退出树洞登录（如果已登录）；
2. 按一般流程登录树洞；
3. 登录完成后，点击「好的」，回到应用主界面；
4. 应用动画和内容正常加载，但不再响应任何点击。

**Additional context**
怀疑与水印遮罩层产生的异常有关，需要进一步调查。

**Comment by Boreas618** [comment]
Fail to reproduce. Debug and release alike. Further discussion is needed.

**Comment by w568w** [comment]
@Boreas618 Try fixing this first. https://github.com/DanXi-Dev/DanXi/commit/f758650608a90d4370a752d27e0bf6b51c8840bd#r96337291

**Comment by w568w** [comment]
I can confirm that the bug disappears if the watermark is disabled.

It seems to be reproducible on Android devices, profile and release mode.

**Comment by Boreas618** [comment]
Trying to fix this in dd7a9e96f934b1f3ef493d05de619c520e6d91bf. 
Moreover, a new option **Fancy Watermark** was introduced in the debug mode to facilitate the test.

**Comment by w568w** [comment]
dd7a9e96f934b1f3ef493d05de619c520e6d91bf seems to fix it already. Close it.
