### ISSUE TITLE
[Feature Request] 新用户引导操作

### ISSUE THREAD

**Issue by Zhuo19** [DanXi-Dev/DanXi#185]
**你的功能需求和某个bug有关吗？**
否

**你想要什么样的功能？**
注意到部分新用户不了解旦夕 App 和树洞的功能和使用方法 ~特别是不知道树洞还可以屏蔽标签的~，可以加入**新用户使用引导**，方便使用。可以包含以下几点：
1. **跳过引导功能**。老用户不需要引导（
2. **介绍账号的不同**。在登录 uis 时，提供一个可展开介绍 uis 账号、复旦邮箱账号、旦夕账号有何不同的页面。
3. **功能展示**。登录 uis 后，展示首页功能（展示一下就行）、日程功能（包括切换学期、设置学期开始时间、加入和删除日程、点击课程查看详情等，可以考虑使用图片展示的形式）
4. **旦夕账户注册引导**。引导用户注册 or 登录 FDUHole（另，目前注册入口**太不显眼了**，建议”注册“和”登录“入口分开）。同样可以展示介绍账号不同的页面。
5. **介绍树洞的功能**。关于功能入口（如通知、排序、收藏、发帖、搜索；回帖、点赞、举报）只需要简单标注一下即可；（可参考 ##1188165）介绍分区和标签的定义和使用；介绍树洞”黑话“（如 #、##、dz、cz）；介绍一些操作，如双击（顶部）”树洞“回顶部、点击（底部）”树洞“刷新。更多内容，引导前往faq查看。
6. **介绍设置界面**。主要是功能展示。
7. 引导功能入口应找个地方放置，便于再次查看。

> 以上基于安卓版撰写

另：写完这些以后，深感这些页面都做上去不是一般的繁琐 orz。可以把 2 和 4 合并，去掉功能展示（因为已经足够直观易懂）（但是设置界面的功能展示应保留），更多侧重于引导基本使用方面。

**Comment by w568w** [comment]
> 在登录 uis 时，提供一个可展开介绍 uis 账号、复旦邮箱账号、旦夕账号有何不同的页面

❌登录 UIS 时用户尚未进入应用。如果是第一次使用（且从未听说过旦夕、树洞等名词），贸然介绍旦夕账号会给人摸不着头脑的感觉。我认为目前的设计是合理的，即在树洞的登录页面进行简短提示。见 #181 。

> 登录 uis 后，展示首页功能（展示一下就行）、日程功能（包括切换学期、设置学期开始时间、加入和删除日程、点击课程查看详情等，可以考虑使用图片展示的形式）

✔这个功能可以做到各个页面的第一次显示中去，尤其是饱受诟病的「日程」页面。

> 引导用户注册 or 登录 FDUHole

❌唯一的登录按钮被置于树洞页面的正中央，对于稍有常识的用户，如何登录/注册树洞几乎是不言自明的。

> 目前注册入口太不显眼了，建议” 注册 “和” 登录 “入口分开

❌目前的设计是为了给用户一致向前（即：任何情况下，全程无需点击返回键）的体验。一般用户无需区分是否注册过，就可以通过「UIS 快捷注册/登录」来完成登录（或者如果有必要，注册并登录）。

如果区分开，用户不得不注意自己是否注册过，稍有不慎就可能有 **「选择注册——输入一堆信息——点击注册——提示已经注册过了——返回到首页——思考密码——选择登录——输入一堆信息——点击登录」** 这一极繁琐的登录流程，或是 **「选择登录——输入一堆信息——点击登录——提示密码错误——多次尝试——多次尝试——返回到首页——思考密码——选择注册——输入一堆信息——点击注册——返回到首页——选择登录——输入一堆信息——点击登录」** 的注册流程。

> 关于功能入口（如通知、排序、收藏、发帖、搜索；回帖、点赞、举报）只需要简单标注一下即可；（可参考 ##1188165）介绍分区和标签的定义和使用；介绍树洞” 黑话 “（如 #、##、dz、cz）；介绍一些操作，如双击（顶部）” 树洞 “回顶部、点击（底部）” 树洞 “刷新。更多内容，引导前往 faq 查看。

⭕我的建议是将内容放到 FAQ 帖子中。客户端可在首次登录时引导用户前往该帖子阅读。

> 介绍设置界面。主要是功能展示。

❌设置页面功能较为集中，介绍的意义不大。各个设置项上的文本本身就是在展示自己的功能。用更长更复杂的语句解释简短的设置项反而有本末倒置之嫌。

**Comment by Zhuo19** [comment]
>❌登录 UIS 时用户尚未进入应用。如果是第一次使用（且从未听说过旦夕、树洞等名词），贸然介绍旦夕账号会给人摸不着头脑的感觉。我认为目前的设计是合理的，即在树洞的登录页面进行简短提示。见 https://github.com/DanXi-Dev/DanXi/issues/181 。

有道理，目前的设计是更为合理的。但考虑到目前许多用户试图使用 UIS 账号密码登录旦夕账号，或许可以在旦夕账号的登录页面，以点击查看或链接 FAQ 的形式介绍账号的不同。

>❌唯一的登录按钮被置于树洞页面的正中央，对于稍有常识的用户，如何登录/注册树洞几乎是不言自明的。

虽然正中央有进入树洞的唯一按钮，但“登录”这一文字介绍可能会使用户产生“这个登录按钮仅限已注册用户使用，注册需要去另外的地方；需要在其他地方找注册入口”的误解（虽然点进去就会看到“注册”二字，但在那个页面中，“注册”和“登录”也被表述为两种行为）。建议修改文案为“开始使用”“进入树洞”一类不含具体操作描述的词语。

>❌目前的设计是为了给用户一致向前（即：任何情况下，全程无需点击返回键）的体验。一般用户无需区分是否注册过，就可以通过「UIS 快捷注册/登录」来完成登录（或者如果有必要，注册并登录）。

我非常认同你希望塑造的“一致向前”的体验，在这一思路下，或许可以对登录页面做一些调整：
- 在登录页面合适（且明显）的位置注明“未注册会自动进入注册流程”；
- （如在技术上可行）在 UIS 已登录的情况下，自动选择（或推荐选择） UIS 快捷注册/登录 选项（可行的话，甚至可以自动判断邮箱后缀，快进到（登录）输入密码/（注册）设置密码页面）。这个方案的优点在于，对于已登录 UIS 的用户，可以相对现版本减少 0-2 步操作（即使是无法减少操作次数的情况，也可以减少用户选择“使用旦夕账号登录”进而需要额外输入一次学邮的情况）；
- 另一或许可行的方式是，直接呈现旦夕账号的登录页面，并采用（类似树洞网页端的）两步填写模式，即先输入邮箱，然后点击“下一步”，由程序识别用户是否注册过，然后继续对应的注册/登录流程；并将“UIS 快捷注册/登录”作为该页面上的一个快捷按钮。这一方案的优点是直奔主题，缺点是无法一次性输入所有信息、以及本可使用 UIS 快捷注册/登录的用户可能会忽略快捷操作选项产生额外操作（可以考虑和上一提议结合以解决该问题）。
（另，在现版本中，如选择“使用旦夕账号登录”并输入未注册的账号密码，无法自动跳转注册，仍需使用返回键；更加严重的问题似乎是仅 FDUHole 新用户可能会陷入以下困惑中：”由于未登录 UIS 忽略 UIS 快捷登录选项——使用旦夕账号登录——找不到注册入口——尝试输入学邮和密码——提示未注册”，如果足够幸运的话，可能才会接着”返回上一步——试着点击 UIS 快捷注册/登录——点击“我的学校邮箱不在列表中”——完成注册流程“。

其他的一些（与本讨论内容不大相关的）小问题：
- “UIS 快捷注册/登录”和“使用旦夕账号登录”并列，可能会产生一种“这是两种账号系统”的错觉（？
- 根据[《App违法违规收集使用个人信息行为认定方法》](http://www.scio.gov.cn/xwfbh/xwbfbh/wqfbh/42311/44109/xgzc44115/Document/1691066/1691066.htm)中的”三、4“，UIS 登录界面的“登录即表示您已阅读并同意隐私政策和使用条款”可被认定为“未经用户同意收集使用个人信息”。~~（但似乎目前很多 App 都是这样的，所以应该也没啥问题）~~

>⭕我的建议是将内容放到 FAQ 帖子中。客户端可在首次登录时引导用户前往该帖子阅读。
>❌设置页面功能较为集中，介绍的意义不大。各个设置项上的文本本身就是在展示自己的功能。用更长更复杂的语句解释简短的设置项反而有本末倒置之嫌。

同意（关于设置页面，我原本的意思是侧重于引导用户查看设置页面并自行了解有关功能，因为我发现不少人不知道设置页面可以屏蔽标签）。或许可以一并归入 FAQ 中。

**Comment by KYLN24** [comment]
## 1

> 在登录 uis 时，提供一个可展开介绍 uis 账号、复旦邮箱账号、旦夕账号有何不同的页面
> 
> ❌登录 UIS 时用户尚未进入应用。如果是第一次使用（且从未听说过旦夕、树洞等名词），贸然介绍旦夕账号会给人摸不着头脑的感觉。我认为目前的设计是合理的，即在树洞的登录页面进行简短提示。见 https://github.com/DanXi-Dev/DanXi/issues/181 。

App 现阶段打开后直接要求登录复旦 UIS 账户，则存在以下几个问题：

1. 使 “登录旦夕 App（一开屏让登录的那个账户）” 和 “登录旦夕账户” 这两个表述的语义存在显著差异，由于这两个表述在字面上存在极大的相似，这非常容易为用户带来歧义与混淆。
2. 使 “旦夕账户” 的语义容易产生歧义与混淆。用户倾向于认为打开旦夕 App 登录的账户就是旦夕账户

事实证明，这确实已经为用户带来了混淆，而且在用户群中已经达到了足以令本项目主力开发者 @w568w 愤怒的规模。

我**建议在 App 初次打开后，弹出可以登录两个账户的选项，并解释登录哪一个账户会启用哪些功能。**这样的好处有：

1. 使 “旦夕账户” 与 “复旦大学 UIS 账户” 在旦夕 App 中处于并列的位置，消除歧义。
2. 使用户可以根据自己的需求登录账户以启用对应的功能。
  - 仅使用旦夕服务的需求是存在的，而现在是通过登录一个占位符 UIS 账户的方式来实现，我认为这个设计很不合理
3. 可以在设置页面中灵活地登录或退出其中的某一账户。
  - 现阶段，在已登录校园服务的状态下仅退出 UIS 账号非常复杂。这需要退出 UIS 账户并重新登录旦夕账户。而在不登录 UIS 账户的情况下登录了旦夕账户，想要重新登录 UIS 账户也非常麻烦。

## 2

> 引导用户注册 or 登录 FDUHole
> 
> ❌唯一的登录按钮被置于树洞页面的正中央，对于稍有常识的用户，如何登录/注册树洞几乎是不言自明的。

由于用户必然拥有 UIS 账户，因此在 UIS 账户和旦夕账户的语义被混淆的情况下，用户会认为自己必然拥有“能拿来登录旦夕的账户”。他们会不断地尝试输入自己 UIS 的账户和密码，甚至会尝试自己的复旦大学教育邮箱密码，并在提示密码错误或用户不存在后认为是旦夕的问题。

这一问题的根源在于我们没有从一开始做好 “UIS 账户” 和 “旦夕账户” 的区分。因此，**这更加表现了制作 “1” 中提到的并列账户引导页面的必要性。**

## 3

> 目前注册入口太不显眼了，建议” 注册 “和” 登录 “入口分开
> 
> ❌目前的设计是为了给用户一致向前（即：任何情况下，全程无需点击返回键）的体验。一般用户无需区分是否注册过，就可以通过「UIS 快捷注册/登录」来完成登录（或者如果有必要，注册并登录）。
> 
> 如果区分开，用户不得不注意自己是否注册过，稍有不慎就可能有 「选择注册——输入一堆信息——点击注册——提示已经注册过了——返回到首页——思考密码——选择登录——输入一堆信息——点击登录」 这一极繁琐的登录流程，或是 「选择登录——输入一堆信息——点击登录——提示密码错误——多次尝试——多次尝试——返回到首页——思考密码——选择注册——输入一堆信息——点击注册——返回到首页——选择登录——输入一堆信息——点击登录」 的注册流程。

UIS 快捷注册/登录依赖 API Key，存在的安全风险。案例：22 级新生在没有实际获得学邮的情况下已经注册了旦夕账户。**建议取消快捷注册/登录**。

让用户无需区分其是否注册过，会导致用户不知道自己是否注册过。事实证明，许多用户常常不知道自己注册过旦夕账户（因为他们已将旦夕账户与 UIS 混淆，所以觉得旦夕账户是一个从未听说的新概念，而尝试在自己已经被自动注册了旦夕账户的情况下注册旦夕账户）

用户区分自己是否注册过和一致向前的用户体验并不冲突。**一个可能的流程是**：

点击 “登录” - 输入学邮 - 检测是否注册过 - 已注册：输入密码登录 - 未注册：提示未注册，输入密码注册后登录

上面介绍的流程可以让用户清晰地知道自己正在登录还是没有帐户需要注册。

## 4

> 介绍设置界面。主要是功能展示。
> 
> ❌设置页面功能较为集中，介绍的意义不大。各个设置项上的文本本身就是在展示自己的功能。用更长更复杂的语句解释简短的设置项反而有本末倒置之嫌。

### a

设置页面并没能充分地展示自己的功能。旦夕账户被纳入 “树洞” 这一这点选项中，这存在以下问题：

1. 旦夕 App 中，旦夕账户并不只用于树洞，还用于与树洞在 UI 上处于并列关系的 “蛋壳课评” 之中。语义上不宜纳入树洞折叠选项中
2. 旦夕 App 中，“旦夕账户” 的设置较 “UIS　账户”　过于隐蔽，会反复强化用户认为　“UIS　账户”　就是　“旦夕”　中要用到的唯一账户的印象

**建议参考 Swift 版的 UI，将旦夕账户与 UIS 账户在设置中置于并列的位置。**

### b

树洞选项的　NSFW 选项语义不明，开启后并不只会印象贴有 *NSFW 标签的内容，**建议明确指出该选项会影响带有 * 标签的内容。**

**Comment by w568w** [comment]
后续开发见 #252。

另外，argue 时如果有和本 issue 所讨论的「引导」无关的功能和其他要求，请另开 issue，否则会使 issue 复杂到无法追踪。请简明扼要地概括所有需求。@KYLN24
