### ISSUE TITLE
[BUG] 连续课程没有区分教室

### ISSUE THREAD

**Issue by JingYiJun** [DanXi-Dev/DanXi#188]
**描述 Bug**
上午三节课在HGX507，接下来两节课在逸夫楼，旦夕的课程连在一起了

**截图**
旦夕课表
![787e71c8186ac39c58b66b2ac094900](https://user-images.githubusercontent.com/19527729/214761764-83b62a71-fa4b-4e89-9fa3-532bdde1f016.jpg)
教务处课表
![image](https://user-images.githubusercontent.com/19527729/214761825-adc24917-3693-4c08-a678-1d700f5cf6f2.png)

**系统信息**
和系统应该没关系
 - 设备型号：Xiaomi 12S Pro
 - 系统版本：MIUI 14.0.4
 - 旦夕版本（见「设置-关于本应用」）：1.3.11 1.3.10

**Comment by w568w** [comment]
和合并算法有关，这里之前只考虑了课程名相同：

https://github.com/DanXi-Dev/DanXi/blob/01c9f6525bc3535ce2527d27b0d11b8cc524e221/lib/widget/time_table/schedule_view.dart#L175-L178
