### ISSUE TITLE
🖍迁移至 Material 3

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#189]
# 背景
目前在升级至 Flutter 3.7 后，发现部分 UI 仍保有 Material 2 的设计习惯，在 Material 3 控件中显得极为突兀；另外也出现了相关配色问题，影响视觉体验，需要及时解决以发布新版。

# 指引
任何相关 UI 问题的现状和解决都应在本贴下记录，较难以解决的问题可另开 issue，链接到本 issue 下。

任何相关修复 commit 都应带有本 issue 号，但应小心不要关闭此 issue，Commit Message 示例：

```
fix: links should not be underlined in post list page

Related to #186.
```

# 📑问题列表
- [x] 帖子列表上各个帖子中、各个 BottomSheet 中（如点击帖子编辑器中的「TeX」后弹出的）的链接均带有下划线
- [x] 帖子列表中的分割线过于明显
- [x] [Material Dark] Markdown 引用块文本颜色为白色，看不清
- [x] #190
- [ ] #192
- [x] #193
- [x] #195

**Comment by Boreas618** [comment]
3 issues were fixed. The rest demand reproduction.

**Comment by w568w** [comment]
> 3 issues were fixed. The rest demand reproduction.

Wonderful! 🚀 I will investigate the rest of them, since they are Android-specific.

**Comment by w568w** [comment]
#192 is unable to be reproduced and quite trivial. 

We have basically fixed them all.

**Comment by w568w** [comment]
只剩一个 issue 了。本 issue 的必要性不大，故关闭。
