### ISSUE TITLE
[BUG] UIS/数据抓取相关bug汇总

### ISSUE THREAD

**Issue by kavinzhao** [DanXi-Dev/DanXi#19]
在以下情况下，可能会产生不预期的错误结果：
- [x] UIS登录时提示“弱密码” (unconfirmed - needs investigation)
- [x] 首次登录后可能出现空白UI (seen - needs investigation)
- [x] 复活码未开通 (confirmed)
- [x] 某些情况下，打开应用时会crash [QRCodeRepository.dart] (confirmed - needs investigation)

**Comment by w568w** [comment]
需要一份复活码未开通时的页面源码，否则不太容易修复bug2

**Comment by w568w** [comment]
❓ 打开 QRCode 的时候崩溃的 bug 还没有修复吗

**Comment by kavinzhao** [comment]
>  ❓ 打开 QRCode 的时候崩溃的 bug 还没有修复吗

我昨天微信发你截图了🤦

**Comment by w568w** [comment]
> 
> 
> > ❓ 打开 QRCode 的时候崩溃的 bug 还没有修复吗
> 
> 我昨天微信发你截图了🤦

看起来似乎没有问题？无法复现。

**Comment by w568w** [comment]
已经找到问题，是手表的问题🤦

**Comment by kavinzhao** [comment]
Closed via 165b6a3
