### ISSUE TITLE
[BUG] [Android] Release 版中首次启动应用时，`showPlatformModalSheet` 无弹出 / 收回动画

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#195]

**Comment by singularity-s0** [comment]
合理怀疑是性能问题

**Comment by w568w** [comment]
> 合理怀疑是性能问题

但是从第二次启动就恢复正常了。着色器预热也是要有动画才能预热吧……

**Comment by singularity-s0** [comment]
> > 合理怀疑是性能问题
> 
> 
> 
> 但是从第二次启动就恢复正常了。着色器预热也是要有动画才能预热吧……

可能第一次也有动画但是卡没了，毕竟没道理只有第一次没动画

**Comment by w568w** [comment]
Upstream：https://github.com/flutter/flutter/issues/119094

**Comment by w568w** [comment]
Haven't tested if it can be reproduced but, it should be fixed since https://github.com/DanXi-Dev/DanXi/commit/4a8c8404524646e261c5d6e20fdd3daa15f73d18.
