### ISSUE TITLE
[BUG] 设置界面无法切换语言

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#196]
**描述 Bug**
在设置页面选择新的语言后，不会立刻生效，而是要等到应用重新启动后才会生效。

**复现步骤**
复现该 Bug 的步骤：
1. 到设置页面；
2. 选择「语言」；
3. 任选一种其他语言；
4. 「语言」下的当前选项文本变化，但应用本身语言无变化；
5. 退出应用重新进入，语言发生了切换。

**Comment by w568w** [comment]
> Is this an iOS-specific issue?

Nope. I only test it on Android.

**Comment by singularity-s0** [comment]
Why don't we just tell user that the setting only take effect after restart

**Comment by w568w** [comment]
> Why don't we just tell user that the setting only takes effect after restart

@Boreas618 has made efforts to provide a instantaneous language switching experience. See if he could fix it.
