### ISSUE TITLE
[Feature Request] 评教系统

### ISSUE THREAD

**Issue by singularity-s0** [DanXi-Dev/DanXi#200]
**你的功能需求和某个bug有关吗？**
否

**你想要什么样的功能？**
非WebView版本的蛋壳

**Comment by ivanfei-1** [comment]
## 进度追踪：

- [x] 重构 course model
- [x] 蛋壳首页
- [ ] 课程搜索
- [ ] 课程分类页
- [ ] 课程详情页
- [ ] 课程评价编辑

**Comment by HydrogenC** [comment]
UI part already finished at [HydrogenC/DanXi](https://github.com/HydrogenC/DanXi)
![微信图片_20230918203536](https://github.com/DanXi-Dev/DanXi/assets/33123710/bfc20fe1-cc0b-446b-ad5d-c9a9e0adead8)
