### ISSUE TITLE
正则表达式性能低下

### ISSUE THREAD

**Issue by singularity-s0** [DanXi-Dev/DanXi#201]
目前，由于dart正则表达式解析性能较低，树洞页面渲染每张卡片需要5-6ms，严重影响UI流畅度。

目前对正则表达式依赖较大的部分包括：
- Markdown语法解析
- 日期解析

若移除上述两处解析，则渲染时间可以降低到1ms。

潜在的解决方案包括：
1. 不管
2. 采用 Isolate 在额外进程中完成解析
3. 传到 Native 完成解析
4. 由后端发送不需要解析的数据

但显然都不是很理想。需要其他办法解决此问题。

**Comment by w568w** [comment]
`question` tag is for issues too brief to get any useful information. Use `help wanted` to declare that you believe it cannot be coped with by yourself.

**Comment by Boreas618** [comment]
Why is the third approach not ideal?

**Comment by w568w** [comment]
这个问题有任何在 1.4.0 中必须解决的必要吗？如果没有，我建议从 Milestone 中移除。

**Comment by Boreas618** [comment]
没有
