### ISSUE TITLE
[BUG] 在 M1 Mac 上无法访问 FDUHole

### ISSUE THREAD

**Issue by singularity-s0** [DanXi-Dev/DanXi#202]
**描述 Bug**
所有树洞相关的网络请求会立刻返回，且`status`为`null`，UIS请求不受影响。

**复现步骤**
复现该 Bug 的步骤：
1. 在 M1 Mac 下载旦夕
2. 登录树洞
3. 出现错误

**截图**
![img_v2_61f702ca-c955-46f2-b4c5-8689af34d50g](https://user-images.githubusercontent.com/12184989/216649631-7ea55537-ac87-4ba6-82ea-5dcd76fe34a7.png)

**系统信息**
 - 设备型号：M1/M2 Mac
 - 系统版本：Unknown
 - 旦夕版本（见「设置-关于本应用」）：1.3.11(331)

**Comment by w568w** [comment]
看起来像是权限问题。确定设置了正确的权限吗？macOS 上运行 iOS 应用是否需要额外配置域名？

**Comment by singularity-s0** [comment]
> 看起来像是权限问题。确定设置了正确的权限吗？macOS 上运行 iOS 应用是否需要额外配置域名？

排除该可能性，因为以往版本可以正常运行

**Comment by w568w** [comment]
因为开发团队缺少设备，无法复现。

**Comment by w568w** [comment]
已经复现，原因是 UserAgent 中带有中文「版本」。应该删除或编码非 ASCII 字符。

**Comment by singularity-s0** [comment]
计划采用 Percent Encoding

**Comment by singularity-s0** [comment]
Attempted fix in d8121cd1
