### ISSUE TITLE
[BUG] [Android] 转到过高楼层时 App 卡死

### ISSUE THREAD

**Issue by QLTyrone** [DanXi-Dev/DanXi#205]
**此Issue搬运自飞书原《功能需求和bug修复建议》文档**

**备注**
比如前往 ##1728616（这个只是用来举例的） 时，安卓版 App 会卡死

**提出部门**
社区运营部

**Comment by w568w** [comment]
重复 #143 .

目前我们没有好的解决办法，相关讨论见 https://github.com/DanXi-Dev/DanXi/pull/162#issuecomment-1172829456 。这也是 iOS 决定重写而非继续开发 Flutter 版的原因之一。
