### ISSUE TITLE
[Feature Request] 锁定帖子

### ISSUE THREAD

**Issue by QLTyrone** [DanXi-Dev/DanXi#210]
**此Issue搬运自飞书原《功能需求和bug修复建议》文档**

**备注**
主要是用来发禁止回复的公告。如果要开发这个的话，需要在第三版公约中同步说明一下

**提出部门**
社区运营部

**Comment by w568w** [comment]
后端问题，请转移至后端。

**Comment by w568w** [comment]
Upstream：<https://github.com/OpenTreeHole/treehole_next/issues/12>。
