### ISSUE TITLE
[BUG] 封禁时的 division id 来源错误

### ISSUE THREAD

**Issue by KYLN24** [DanXi-Dev/DanXi#215]
**描述 Bug**
app 调用封禁 api 时，传递的 division id 参数是旦夕 app 当前处于的分区，而非封禁时所处的 hole 具有的 division id。这会导致通过搜索功能跳转到对应帖子并执行封禁时，会封禁这个用户在管理员的旦夕 app 所处的分区的权限，而非这个帖子所在的分区的权限。

**复现步骤**
复现该 Bug 的步骤：
管理员打开圆桌分区，通过搜索跳转一个站务区的帖子，并封禁。查看 http log，发现division id 参数为 2，而非 4。

**系统信息**
 - 设备型号：iPhone 12
 - 系统版本：iOS 16.3.1
 - 旦夕版本（见「设置-关于本应用」）：1.3.11

**Comment by w568w** [comment]
这是由于上游仓库仍在根据封禁请求中的分区参数，而不能根据楼层号封禁分区权限。见

https://github.com/OpenTreeHole/treehole_next/blob/92f61e7250b3f974148999c84745517aac3cf3f2/apis/penalty/api.go#L76-L83

请到上游仓库提出相关更改。否则客户端将不得不请求两次（第一次：获取对应分区号，第二次：请求封禁）来完成封禁操作。
