### ISSUE TITLE
[Feature Request] 在隐藏的贴子内提供 UI 提示

### ISSUE THREAD

**Issue by KYLN24** [DanXi-Dev/DanXi#223]
**你的功能需求和某个bug有关吗？**
`[是/否]` 否

**你想要什么样的功能？**
在隐藏的贴子内提供 UI 提示，比如在标题 #xxxx 后面加一个“已隐藏”的字样

**Comment by w568w** [comment]
这个显示的作用是什么？

**Comment by KYLN24** [comment]
1. 让浏览该洞的用户知道该洞已被隐藏
2. 提示管理员该洞已被隐藏，无需重复操作
