### ISSUE TITLE
[Feature Request] 重启 macOS(Intel) 版的发布

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#224]
**你的功能需求和某个bug有关吗？**
否

**你想要什么样的功能？**
之前由于 macOS 版[受众人数较少](https://github.com/DanXi-Dev/DanXi/commit/4e14e3cc62b0be2d699fb727b74524ffb9331855)、[框架不成熟](https://github.com/DanXi-Dev/DanXi/commit/392c1795250e40cd00df9a202dedb1c7f2de7484)等原因，暂停了该版本的发布。现在是否有可能构建 macOS(Intel) 的专用版本？

cc @singularity-s0 @Boreas618

**Comment by singularity-s0** [comment]
目前所使用的许多包与macOS兼容性较差。除非有足够的Intel Mac用户群体，否则没有必要专门适配一个即将退出历史舞台的平台。

**Comment by w568w** [comment]
希望再 Argue 一次该 issue，理由如下：

1. 目前 M1 macOS 设备上存在恶性 Bug（#202），最新版还未发布，因此所有 M1 用户都无法使用树洞，这一情况已经持续了**至少 6 个月，而发版还有一段时间**；
2. 现有的其他解决方法均不适用：
    - Swift 发布 macOS 版：目前时间不明确，开发者表示「不太行，虽说跨平台但是有很多细节是不一样的，得专门处理」「硬编译出来的整个排版都是乱的」，而恶性 bug 的修复亟待发布；
    - 发布 `.ipa` 包：M1 似乎不允许侧载未签名的 Apple Store 应用；
    - 加入 TestFlight：可以，但人数受限，内测群人员混杂，不好管理；
    - 立刻增发一版修复版本：增发一版后所有用户都会收到，相当于公测。对于开发者无法复现的 bug，相当于**直接发布未经检验的代码到公众中去，有时发版后会发现无法解决问题，等用户反馈后又要再发一版，费时费力**。

因此，发布 Intel 版可以让这部分 M1 macOS 用户也体验到最新的内测版本，**对用户来说是没有害处的**。并且在当前来看，出现恶性 bug 无法解决的情况，就只能临时发版，而有时往往需要先内测，甚至在用户的环境下测试，这样的情况现有的解决方案都不合适。

> 目前所使用的许多包与 macOS 兼容性较差

具体是指哪些包？我之前在 Linux 上测试的结果是基本功能都能正常使用，**如果 Linux 这么小众的平台都能无修改直接编译运行**，那么「许多包与 macOS 兼容性较差」的说法我认为你可能需要具体解释一下。

> 除非有足够的 Intel Mac 用户群体

有关 Intel Mac 的群体 vs M1 Mac 群体的大小，我没能找到准确数字，但 [DigiTimes](https://www.digitimes.com/news/a20221107PD207.html) 给出的数字是 M1 的市场份额为 11.8%。即便我们将这解释为全体 PC 市场份额（原文未说明），那么 [Apple 笔记本 2022 年末的市场总份额为 27%](https://www.statista.com/statistics/267023/global-pc-shipments-since-2006-by-vendor/)，也**只占到 43% 的 Apple Mac 用户**。

> 没有必要专门适配一个即将退出历史舞台的平台

硬件更新换代和软件不同，具有较长的滞后性，通常 3-5 年才为一个周期。对于软件求新的想法是可取的，因为大部分用户可以自主升级到最新版，Drop 旧版本无可厚非，但**即便 Apple 声称 Drop 了 Intel，所有人手里的上百万台 Intel Macbook 也不会自动变成 M1 驱动，Intel 也不会「瞬间」退出历史舞台。我看不出在目前我们放弃掉一个具有至少 57%+ 甚至 80%+ 占有率的平台的意义。**
