### ISSUE TITLE
[BUG] Android 13+ 无法保存图片

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#225]
**描述 Bug**
Android 13+ 上分区存储被强制启用，原先的 `WRITE_EXTERNAL_STORAGE` 权限已被废弃，最佳实践为[声明相关权限](https://developer.android.google.cn/training/data-storage/shared/media?hl=zh-cn#storage-permission)，然后自行使用 [Content Resolver](https://developer.android.google.cn/training/data-storage/shared/media?hl=zh-cn#toggle-pending-status) 将图片[导出](https://developer.android.com/training/data-storage/use-cases?hl=zh-cn#export-media-files-to-device)到合适目录。

目前 Flutter 没有成熟的库完成这一操作。可能不得不自行编写兼容逻辑。

**系统信息**
 - 设备型号：n/a
 - 系统版本：Android 13
 - 旦夕版本（见「设置-关于本应用」）：1.3.11

**Comment by kooWZ** [comment]
![A359130EF5CF058441F76D68723B9DF7](https://user-images.githubusercontent.com/60533182/226894221-97448e80-3424-40e4-912c-b04946979e0b.jpg)
或许可以用这个权限？
https://developer.android.com/training/data-storage/manage-all-files?hl=zh-cn
