### ISSUE TITLE
[Feature Request]尽快取消数字水印

### ISSUE THREAD

**Issue by TigerBest** [DanXi-Dev/DanXi#228]
**你的功能需求和某个bug有关吗？**
`[否]`

**你想要什么样的功能？**
旦夕从2023年2月3日发布的1.3.11版本开始添加“实验性”的数字水印，水印内容为个人ID。若无必要请尽快移除该特性，或至少不应该以肉眼可见的形式直接显示在主页。

**Comment by w568w** [comment]
> 若无必要请尽快移除该特性

与 FDUHole 公约要求相契合。由于 FDUHole 是目前旦夕唯一的（硬编码的）树洞服务提供方，这一功能是有必要的；

> 不应该以肉眼可见的形式直接显示在主页

目前我们没有找到合适的方案。如果你找到了，欢迎告诉我们或者提交 PR。
