### ISSUE TITLE
[Feature Request] 搜索自杀关键词时弹出救援热线

### ISSUE THREAD

**Issue by KYLN24** [DanXi-Dev/DanXi#235]
搜索自杀关键词时弹出救援热线

**Comment by Boreas618** [comment]
In commit 52f547fe74e7aab2e2825e600c7a7c042f705186, we introduced **DanXi Care** on the search page.

Some **care words** are suggested to detect potential suicide-like incidents. You can modify this list in the source code's assets or on https://github.com/DanXi-Dev/DanXi-Backend/blob/main/all.json.

Future directions include:

- More professional care messages (the current message is generated by GPT-4).
- Detection of care needs when sending posts.

<img width="353" alt="Screenshot 2023-07-19 at 4 08 17 PM" src="https://github.com/DanXi-Dev/DanXi/assets/98612013/bc517e20-8b29-49cc-9483-ff0220a5ae3c">

**Comment by w568w** [comment]
这个实现完了吗？如果实现完了请 close。

**Comment by kooWZ** [comment]
> 这个实现完了吗？如果实现完了请 close。

文案还需要调整
之前群里讨论的文案还没放进去
