### ISSUE TITLE
[BUG]「已隐藏」标签对所有用户可见

### ISSUE THREAD

**Issue by Zhuo19** [DanXi-Dev/DanXi#238]
**描述 Bug**
目前版本中，「已隐藏」标签对所有用户可见，可能导致用户刻意地想要传播 ta 见到的「已隐藏」内容，不符合功能设计的初衷（降低相关帖讨论度，但保留一定的可见性）。建议使该标签仅对管理员可见。
如果可以的话，希望本月内完成。

**Comment by w568w** [comment]
需要讨论该功能的必要性。

**Comment by w568w** [comment]
已经在上游完成。客户端不做处理。
