### ISSUE TITLE
[Feature Request] 注册前答题

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#239]
**你的功能需求和某个bug有关吗？**
`否`

**你想要什么样的功能？**
为了帮助用户快速熟悉树洞，用户注册前，要求其完成一些从在线题库中选择的题目（也可以硬编码在 App 中）。

@Zhuo19 等维护者将负责编写题库。

**Comment by w568w** [comment]
Upstream: https://github.com/OpenTreeHole/treehole_next/issues/100.

**Comment by w568w** [comment]
由于在答题权限设计上存在分歧，我不再负责此项中 API 对接和检测埋点的部分。

**Comment by w568w** [comment]
根据最近一次 Meeting 的决议，该功能由于开发进度缓慢，暂时延缓启用。可放入下个版本中。

**Comment by w568w** [comment]
我近期无意完成此项。

**Comment by KYLN24** [comment]
感觉可以暑假再做，24级新生入学前完成。这个还需要放在1.4.3吗？

**Comment by w568w** [comment]
> 可以暑假再做，24 级新生入学前完成

目前后端测试服已开启此功能，应当认为有必要做。

**Comment by HydrogenC** [comment]
这般还有必要继续加功能吗，还是全力写重构版

**Comment by ivanfei-1** [comment]
> 这版还有必要继续加功能吗，还是全力写重构版

重构所花的时间非常多，所以我们还需要现有的版本继续运转。

**Comment by HydrogenC** [comment]
What if the user didn't answer a question correctly? Do we show the correct answer and require to select again or just show the answer and allow the user to advance to the next question?

**Comment by w568w** [comment]
> 这版还有必要继续加功能吗，还是全力写重构版

两者平行进行，不冲突。

> What if the user didn't answer a question correctly? Do we show the correct answer and require to select again or just show the answer and allow the user to advance to the next question?

I think the behavior should be kept consistent with the Swift version.

cc @fsy2001 Can you have a look?

**Comment by HydrogenC** [comment]
明白。但是按照这种设计，似乎是用不到 `/register/questions/_answer` 这个 api，纯客户端判断就够了。
