### ISSUE TITLE
[Feature Request] 对于时间过远的树洞直接显示发布的时间

### ISSUE THREAD

**Issue by KYLN24** [DanXi-Dev/DanXi#255]
对于时间过远的树洞，目前会显示 xxxd 这样一个模糊的天数。或许超过一天的可以直接显示具体的时间？

**Comment by w568w** [comment]
参考 <https://github.com/DanXi-Dev/DanXi/blob/main/lib/util/opentreehole/human_duration.dart>。没有明白你想做出什么更改。

**Comment by KYLN24** [comment]
现阶段，大于1天的floor只会精确到天，建议统一改为
2023/07/23 23:51 这种形式，精确到时间

如果觉得只显示到模糊的天数就够了，也可以直接关闭本 issue as not planned

**Comment by kooWZ** [comment]
1天的时间是否有点短
我感觉7天或者14天以上再改成精确时间比较好

**Comment by w568w** [comment]
能否改成长按时显示具体时间？（在 Bottom Sheet 顶部）

@singularity-s0 @Boreas618 这是否符合 Cupertino 惯例做法？

**Comment by singularity-s0** [comment]
iOS平台默认短时间显示方法如下：
- 对于当天的内容，采用 hh:mm
- 对于昨天的内容，显示 Yesterday
- 对于一周内的内容，仅显示周几
- 对于一周以外的内容，采用 yyyy/MM/dd 或者当地日期格式

**Comment by w568w** [comment]
> 不会采用长按显示具体时间的做法

我的意思是，在 Bottom Sheet 顶部显示一些类似帖子元信息的文本，其中包含时间。

如示意图：

![图片](https://github.com/DanXi-Dev/DanXi/assets/8389787/0b9be525-e2b1-4608-a273-a35c38028934)

**Comment by singularity-s0** [comment]
看上去与本issue的提议并不冲突

**Comment by w568w** [comment]
那我的建议是不更改时间的显示方式，仅增加显示具体帖子信息的选项（如上图）。
