### ISSUE TITLE
[Feature Request] 动态修改 opentreehole 的请求 URL

### ISSUE THREAD

**Issue by JingYiJun** [DanXi-Dev/DanXi#260]
**你的功能需求和某个bug有关吗？**
否

**你想要什么样的功能？**
目前 opentreehole repository 的 _BASE_URL, _BASE_AUTH_URL, _IMAGE_BASE_URL 都是写死的 string，只能用与正式服，不方便使用测试服调试。希望可以提供一个动态修改这三个 URL 的页面。

**Comment by w568w** [comment]
测试功能不是发版必需的，先从 milestone 中移除。
