### ISSUE TITLE
[Feature Request] 管理操作改为页面

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#261]
目前的管理操作都使用输入框和对话框来进行，容易误触，且不便于在管理时查看帖子内容。可以改成如 Swift 版一样的页面或 Bottom Sheet，如下图。

![图片](https://github.com/DanXi-Dev/DanXi/assets/8389787/69679156-4690-4e09-b888-edf51cabba8b)

**Comment by HydrogenC** [comment]
I believe I could try doing this.

**Comment by w568w** [comment]
I am afraid that it will not be reviewed in time. Removed from milestone.

Anyway, we can publish "sub-version" for admins at any time, not specifically 1.4.0 :)
