### ISSUE TITLE
[Feature Request] 上架 Google Play

### ISSUE THREAD

**Issue by singularity-s0** [DanXi-Dev/DanXi#263]
**你的功能需求和某个bug有关吗？**
否

**你想要什么样的功能？**
现平安复旦已经取消，可以再次上架Google Play商店

**Comment by w568w** [comment]
需要一个账号注销的页面。

Blocked by https://github.com/OpenTreeHole/auth_next/issues/10.

**Comment by w568w** [comment]
已经临时创建一个飞书问卷，移除上游必选依赖。

**Comment by w568w** [comment]
已经上架：https://play.google.com/store/apps/details?id=io.github.danxi_dev.dan_xi
