### ISSUE TITLE
首次使用「日程」页面时，提供功能展示

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#268]

**Comment by w568w** [comment]
@cryindevil 你可以来做这个吗？

**Comment by cryindevil** [comment]
收到，我来尝试一下，如果有问题来咨询您可以吗，是否有截止时限?



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月03日 09:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [DanXi-Dev/DanXi] 首次使用「日程」页面时，提供功能展示 (Issue #268) |

@cryindevil 你可以来做这个吗？

**Comment by w568w** [comment]
这个 issue 属于 https://github.com/DanXi-Dev/DanXi/milestone/2 的一部分，在那里可以看到总 DDL。

另：团队内无需使用敬词，这会影响沟通效率。直接问「是否有截止时限」即可。

**Comment by w568w** [comment]
> 收到，我来尝试一下，如果有问题来咨询您可以吗，是否有截止时限？

这个 issue 属于 https://github.com/DanXi-Dev/DanXi/milestone/2 的一部分，在那里可以看到总 DDL。

另：团队内无需使用敬词，这会影响沟通效率。直接问「是否有截止时限」即可。

**Comment by cryindevil** [comment]
明白







在 2023-08-03 10:05:50，"w568w" ***@***.***> 写道：

收到，我来尝试一下，如果有问题来咨询您可以吗，是否有截止时限？

这个 issue 属于 https://github.com/DanXi-Dev/DanXi/milestone/2 的一部分，在那里可以看到总 DDL。

另：团队内无需使用敬词，这会影响沟通效率。直接问「是否有截止时限」即可。

**Comment by cryindevil** [comment]
已提交pr，初次提交如有问题望指正
