### ISSUE TITLE
[Feature Request] 空教室：切换日期和座位数显示（和其他to-do）

### ISSUE THREAD

**Issue by kavinzhao** [DanXi-Dev/DanXi#27]
**你的功能需求和某个bug有关吗？**
`[是/否]`否

**你想要什么样的功能？**
简要、清晰地描述你请求增加的功能。
如题

- [x] 切换日期
- [ ] 显示座位数
- [x] 重新设计Material模式下的UI

（其他to-do）
- [ ] 首页显示”本周是第x周”
- [x] 切换校区后刷新subpage_main
- [x] 饭卡余额小于20时标红

**Comment by w568w** [comment]
> 首页显示” 本周是第 x 周”

本条与#12 中的“主页仅显示今天和明天的课程表（已经上过的课不再显示，类似 Up Next），若周末没课，则显示下周 Summary”从某种方面来说重复了

> 显示座位数

数据源在哪里？

**Comment by kavinzhao** [comment]
> > 首页显示” 本周是第 x 周”
> 本条与#12 中的“主页仅显示今天和明天的课程表（已经上过的课不再显示，类似 Up Next），若周末没课，则显示下周 Summary”从某种方面来说重复了

目前暂未支持Up Next功能，谈不上重复，待支持后可以再进行改动。

> 
> 
> 
> > 显示座位数
> 
> 
> 
> 数据源在哪里？

不知道，但小程序里有显示
