### ISSUE TITLE
[BUG] 历史搜索页面overflow

### ISSUE THREAD

**Issue by kooWZ** [DanXi-Dev/DanXi#277]
当历史搜索数量超出一屏时，
https://github.com/DanXi-Dev/DanXi/blob/97c48f6f90a74be6b22559a7d631d66894a6b959/lib/page/opentreehole/hole_search.dart#L133
报overflow，同时内部的ListView不能滚动

**Comment by kooWZ** [comment]
直接用`SingleChildScrollView`把整个Column包上可以修复，但是这样搜索栏也会跟着滚动
我认为理想的效果是搜索栏和“历史记录”字样、”清除“按钮置顶，只滚动内部的`ListView`

**Comment by w568w** [comment]
> 同时内部的ListView不能滚动

有研究过这个的原因吗？是不是 `Flexible` 导致的？

这个组件是在 https://github.com/DanXi-Dev/DanXi/commit/03bb09ce06ef6dccd0875104932b5a155473b84a#diff-302fdaa1d48e266c0964b4a60f43d4f2cdc0217b0042b379adad73c1aa40d1ef 加上的，对 `Flexible` 我确实没啥印象了，你可以替换成 `Expand` 试试看
