### ISSUE TITLE
[BUG] 部分同学生活码加载失败

### ISSUE THREAD

**Issue by kooWZ** [DanXi-Dev/DanXi#279]
报错`Null check operator used on a null value`，但是eCard小程序中可以正常显示

似乎集中在23级同学账号中出现，22级无法复现

方案：
1. 等着，可能是新生某些权限不全等不明原因导致。开学后如果依然报错再进行排查修复
2. 找23级同学提供账号进行debug

**Comment by kooWZ** [comment]
已知22级新生去年暑假时复活码也不能正常加载，但是提示403 Forbidden 而不是null value

**Comment by w568w** [comment]
> 找 23 级同学提供账号进行 debug

不一定需要提供账号，可以让他们开启 DEBUG 模式，发送抓包结果给我们：

1. 「设置」「开源软件许可协议」，长按标题 5 次，直至出现 *Debug Mode Enabled* 提示；
2. 重启应用，触发一次复活码显示；
3. 点击 DEBUG 模式下出现的悬浮按钮，进入 dio 日志页，选择和 `ecard.fudan.edu.cn` 有关日志项，发送 Response 页内容。
