### ISSUE TITLE
[BUG] Linux 上无法使用鼠标做出滑动等操作

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#287]
如题。Linux 上仅能用鼠标滚轮来滚动页面，无法使用鼠标左键直接拖动浏览。

**Comment by singularity-s0** [comment]
为什么在桌面平台上会需要鼠标左键直接拖动浏览？似乎大部分桌面应用均不支持这种操作方式

**Comment by w568w** [comment]
> 为什么在桌面平台上会需要鼠标左键直接拖动浏览？似乎大部分桌面应用均不支持这种操作方式

1. Flutter 鼠标滚轮和触摸板都不支持惯性滚动，我这个笔记本上，手指从触摸板的最上端滑到最下端，旦夕页面才滚动不到一页的距离，体验很差；
2. 有些控件只支持拖动浏览，例如 Banner。
