### ISSUE TITLE
[Feature Request] 添加自托管的应用分析

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#292]
**你的功能需求和某个bug有关吗？**
`否`

**你想要什么样的功能？**
bmob 停止服务以后，一直缺少一个应用分析服务。我们可以在后端上托管分析服务，添加应用分析 SDK，尽量做到 Privacy-friendly。

p.s. 不建议在 FOSS 分支中加入任何 SDK。

Assigns @HydrogenC

**Comment by HydrogenC** [comment]
I'm afraid this has to be delayed to the next version

**Comment by w568w** [comment]
@JingYiJun 你有时间来进行这一项吗？

**Comment by JingYiJun** [comment]
目前暂无意向，aptabase 还没有调通，我认为这个不急

**Comment by w568w** [comment]
目前似乎没有成员有兴趣实现这一功能。如果有兴趣，请评论或 Reopen。
