### ISSUE TITLE
[BUG] Tiny bug collections for 1.4.0

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#299]
收集一些发版前需要解决的零碎问题，这一 issue 在 1.4.0 发布前都不会关闭。

- [x] 点击「分享楼层」或「分享帖子」无反应
- [x] 「重置布局」点击无反应
- [x] Android 系统上，关注一个帖子，然后退出到桌面，等系统通知栏有回复通知时点击通知，打开应用。此时点击帖子进行定位出现两个红色感叹号警告
- [x] 点击一张图片放大查看时，右上角的保存按钮有效。这时只要进行一次旋转屏幕操作（系统开启自动旋转），右上角的保持按钮就变为转动的圆圈表示加载中。退出图片全屏后重新点击图片又可以正常保存。

**Comment by kooWZ** [comment]
> 收集一些发版前需要解决的零碎问题。
> 
> * [ ]  点击「分享楼层」或「分享帖子」无反应

什么叫「无反应」？我这里点击之后会将链接复制到剪切板，并显示已复制的提示

**Comment by w568w** [comment]
> 什么叫「无反应」？我这里点击之后会将链接复制到剪切板，并显示已复制的提示

目前只在 Cupertino 上做了测试，Cupertino 端没有任何复制提示。但我想这不是大问题。

**Comment by HydrogenC** [comment]
After dogfooding the new curriculum board, I feel that it's annoying to have the search bar auto focused. Since this only changes a few lines, a pr would be too complicated for that, could someone with write access disable the autofocusing of the search bar? 
course_search_bar.dart : 71

**Comment by w568w** [comment]
1.4.0 已发布。
