### ISSUE TITLE
[BUG] 课表添加周日课程时出现在选定周的前一周

### ISSUE THREAD

**Issue by JingYiJun** [DanXi-Dev/DanXi#306]
**描述 Bug**
手动设置课表周日的课程时，假如只设置第10周，会出现在第9周的课表页面上

**复现步骤**
复现该 Bug 的步骤：
1. 到课表页面
2. 点击右上角手动添加课程
3. 勾选第10周开课，周日任意时间
4. 课程出现在第9周的课表页面

**系统信息**
 - 设备型号：跟设备没关系
 - 系统版本：跟系统没关系
 - 旦夕版本（见「设置-关于本应用」）：1.14.0 nightly build 336

**Comment by w568w** [comment]
和周日有关吗？我测试了添加到第 10 周周四，是正常的。

这可能是因为教务系统上对周日的定义和我们有所不同而做出的特殊处理：教务服务上的课表中，周日是一周的第一天，而我们的课表中周日是最后一天，因此（教务系统的）第 10 周周日是（我们的）第 9 周最后一天。

**Comment by JingYiJun** [comment]
除了周日以外都是正常的。

能不能稍微修一下，表现一致即可。

**Comment by w568w** [comment]
> 表现一致即可

如何定义表现一致？如果以我们的周划分方式为准，则添加课程到（旦夕显示的）第 10 周周日时，应当保存在（旦夕内部使用数据结构，即教务系统的）第 11 周周日。

**Comment by w568w** [comment]
另 @ivanfei-1 ：如果近期内不准备解决某一问题/给出解决方案/跟进问题讨论，应说明情况，或解除自我 assignment。

**Comment by AInfinity-LilacDream** [comment]
2024.10.11 我正在尝试修bug

**Comment by w568w** [comment]
更新：这是在解决 #217 的过程中，#218 导致的回归。

我们应当要么 (1) 在导入课表的过程中修改所有周日课程的日期，将其向前移动一周再保存；要么 (2) 在手动添加课程的过程中，如果是周日则特殊处理（向后移动一周）。
