### ISSUE TITLE
[Feature Request] Markdown 支持代码高亮

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#309]
在 Markdown 渲染中增加对代码块高亮的支持，以便提高可读性。

实现方法可参考 <https://github.com/flutter/flutter/issues/81755>。

**Comment by w568w** [comment]
原 issue 中提到的 [flutter_highlight](https://pub.dev/packages/flutter_highlight) 最后更新是 2021 年，其 Fork 版，[flutter_highlighting](https://pub.dev/packages/flutter_highlighting) 也已经停止维护约 10 个月。我的建议是迁移到支持代码高亮的 Markdown 库，[markdown_widget](https://pub.dev/packages/markdown_widget)。

**Comment by HydrogenC** [comment]
@cryindevil Are you going to do this recently? If you aren't, maybe I'll have a try.

**Comment by cryindevil** [comment]
> @cryindevil Are you going to do this recently? If you aren't, maybe I'll have a try.

Sure, I may not implementing it recently @HydrogenC

**Comment by HydrogenC** [comment]
@w568w @singularity-s0  
On the website of `flutter_markdown` it says: 
> By default, Markdown is not selectable. A caller may use the following ways to customize the selection behavior of Markdown:
> Set selectable to true, and use onTapText and onSelectionChanged to handle tapping and selecting events.
> Set selectable to false, and wrap Markdown with [SelectionArea](https://api.flutter.dev/flutter/material/SelectionArea-class.html) or [SelectionRegion](https://api.flutter.dev/flutter/widgets/SelectableRegion-class.html).

It seems that there's official support for `SelectionArea`, so is the fork <https://github.com/singularity-s0/flutter_markdown_selectable> still necessary;

**Comment by singularity-s0** [comment]
This may no longer be necessary. You can test this yourself.
