### ISSUE TITLE
[BUG]复活码无法加载

### ISSUE THREAD

**Issue by qingshanlanshan** [DanXi-Dev/DanXi#31]
**Describe the bug**
复活码无法加载
显示“加载失败，点击重试”

**Screenshots**
![Screenshot_20210429-102013](https://user-images.githubusercontent.com/68636377/116494963-95853400-a8d4-11eb-9160-34f46d313bf9.jpg)

**Smartphone (please complete the following information):**
 - Device: Oneplus 8 pro
 - OS: Android 11
 - Version 0.3.1

**Additional context**
点击复活码后亮度自动调高，这个亮度可以由用户决定吗

**Comment by kavinzhao** [comment]
请确认：软件是否是从GitHub下载的最新版？最新版的报错提示信息不应该是这个。

另外，你可以检查一下 微信eHall小程序->复活码 能否正常显示。通常加载失败是由未同意用户协议导致的。
