### ISSUE TITLE
F-Droid doesn't allow mipush

### ISSUE THREAD

**Issue by linsui** [DanXi-Dev/DanXi#310]
DanXi 用的是添加了 mipush 支持的 receive_intent，但 mipush 不开源，所以 F-Droid 的版本要去掉 mipush。我直接改一下 pubspec.lock 里的 commit 就可以吗？或者你单独加一个 flavor？

**Comment by w568w** [comment]
之前合并主分支时忘记删除非自由依赖了，我稍后会处理这个。
