### ISSUE TITLE
[Feature Request] 用于审核的特殊账号

### ISSUE THREAD

**Issue by ivanfei-1** [DanXi-Dev/DanXi#311]
- 设置一个特殊账户用于发版审核，登陆后直接进入游客模式。去除所有学校信息。
- 游客模式登录时报错。
- 隐藏校区信息。
- 简介删除信息。

**Comment by w568w** [comment]
目前看来还有必要吗？

**Comment by w568w** [comment]
从目前情况来看似乎已无必要，暂时关闭。
