### ISSUE TITLE
[BUG] 分享链接跳转

### ISSUE THREAD

**Issue by ivanfei-1** [DanXi-Dev/DanXi#314]
**描述 Bug**
分享链接在网页端跳转到登录页面后无法跳转app，考虑到许多即时聊天软件都会自带浏览器，这应该需要解决。

**Comment by w568w** [comment]
这应该是网页端的问题吧？建议移动到 https://github.com/OpenTreeHole/auth-frontend-next/issues 。

**Comment by w568w** [comment]
请手动移动到网页端 issue 区！从问题描述来看，和客户端无关。
