### ISSUE TITLE
树洞什么时候修好啊

### ISSUE THREAD

**Issue by liunh53** [DanXi-Dev/DanXi#322]
树洞什么时候修好啊

**Comment by w568w** [comment]
你发错位置了，这里是旦夕 App 客户端的仓库，不受理树洞相关问题。

p.s. 有关树洞维护情况，请关注微信公众号 [旦夕茶馆] 或发送邮件至 dev@fduhole.com 询问。截止回复时，还没有明确的维护终止时间表。
