### ISSUE TITLE
[Feature Request] 修改「考试和成绩」的学期

### ISSUE THREAD

**Issue by JingYiJun** [DanXi-Dev/DanXi#329]
当前「考试和成绩」模块中学期为 2022-2023学年 2学期，希望能改为最新的学期。

版本 1.4.0 build 336

**Comment by w568w** [comment]
确定默认学期的相关逻辑（`semesterIdFromCookie`）在这里：

https://github.com/DanXi-Dev/DanXi/blob/38899b656316294345dd44115858d54b2c7f0835/lib/repository/fdu/edu_service_repository.dart#L72-L79

简单来说，该学期不是旦夕硬编码指定的，而是通过**在不提供任何学期 id 相关信息的情况下请求教务系统，然后读取服务器响应中默认设定的 `semester.id` cookie 得到的**。

这和访问教务系统的行为保持一致（即：清空你的所有 cookie，访问教务系统，默认显示的也是 2022-2023 学年 2 学期），目前暂时没有想到比这更好的数据来源。

**Comment by w568w** [comment]
没有收到更多回复，Close as stale.
