### ISSUE TITLE
[BUG] 校车功能无法使用

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#331]
「校车班次」显示加载失败。

**系统信息**
 - 设备型号：Redmi K30 Pro
 - 系统版本：Android 14
 - 旦夕版本（见「设置-关于本应用」）：1.4.0

**Comment by kooWZ** [comment]
信息办返回的数据不规范导致反序列化出错
![image](https://github.com/DanXi-Dev/DanXi/assets/60533182/0b660d50-5247-48b1-9177-b3c9f1ef0b04)
