### ISSUE TITLE
[Feature Request] iOS版迁移至Cupertino或者Material-3

### ISSUE THREAD

**Issue by ivanfei-1** [DanXi-Dev/DanXi#335]
Flutter is going to drop Material-2 soon. We can still force it to use the Material-2 layout in new versions of Flutter for now, but with an appreciable amount of UI bugs, while the existing Material-3 layout looks distinctly weird on iOS. Therefore, consider using Cupertino widgets instead.

Before this issue is closed, the Material-2 branch will be kept with an older version of Flutter, using the Material-2 layout and synchronized with the main branch for iOS, iPadOS, and MacOS distribution.

**Comment by w568w** [comment]
We may do it someday, but I personally have no time working on this.
