### ISSUE TITLE
[Feature Request] Windows版开机启动并缩小到Tray

### ISSUE THREAD

**Issue by YijunYuan** [DanXi-Dev/DanXi#34]
**你的功能需求和某个bug有关吗？**
`否`

**你想要什么样的功能？**
Windows版添加开机启动的功能，并提供默认最小化窗口启动的选项。
此外关于最小化窗口，是否最小化到Tray而不是任务栏更好？或许可以提供选项让用户决定。

**Comment by w568w** [comment]
Working on it.

**Comment by w568w** [comment]
我们所使用的跨平台开发框架 [Flutter](https://flutter.cn/) ，暂时没有提供显示托盘图标的功能，相关功能[正在开发中](https://github.com/flutter/flutter/issues/81644)。由于我们几个开发都不太懂 Windows 原生开发，实现缩小到 Tray 的功能可能需要研究一段时间。   

---
关于开机启动相关功能，应该这几天就能完成。

**Comment by w568w** [comment]
一个月过去了，看起来 Flutter 社区不打算支持这个功能。很遗憾，由于小组内缺乏有 Windows C++/C# 开发经验的同学，我也不太看得懂`Windows 32 User API`的文档，我们只能暂时搁置这个提议。如果你有相关经验，也欢迎提交 [Pull Request](https://github.com/DanXi-Dev/DanXi/pulls) 加入开发。

**Comment by w568w** [comment]
我们找到了潜在的相关解决方案。这个 issue 将被重新提上解决清单里。

**Comment by lijy91** [comment]
可以使用 [`tray_manager`](https://pub.dev/packages/tray_manager) 及 [`tray_manager`](https://pub.dev/packages/window_manager) 这两个插件来实现该功能，插件已支持三大桌面平台。
