### ISSUE TITLE
[BUG] 考试和成绩报错

### ISSUE THREAD

**Issue by JingYiJun** [DanXi-Dev/DanXi#355]
**复现步骤**
复现该 Bug 的步骤：
1. 点开考试和成绩
2. 选择之前的学期

**截图**
如果方便的话，你可以添加截图。
![Screenshot_2024-05-26-20-26-32-707_io.github.danxi_dev.dan_xi-edit.jpg](https://github.com/DanXi-Dev/DanXi/assets/19527729/4acac193-a508-46d6-8da2-8ffc3b02ded7)

**系统信息**
 - 旦夕版本（见「设置-关于本应用」）：1.4.2 build 338

**Comment by w568w** [comment]
请提交「详细信息」的截图。

**Comment by w568w** [comment]
由于长期未回复，且无法复现，关闭该问题。如仍存在问题请 Reopen。
