### ISSUE TITLE
[BUG] 新版本仍然不能提交评教修改

### ISSUE THREAD

**Issue by 00sqh** [DanXi-Dev/DanXi#360]
复现该 Bug 的步骤：
1. 到已评教页面
2. 点击 修改
3. 选择 提交
4. 出现错误

**截图**
<img width="521" alt="屏幕截图 2024-06-24 134418" src="https://github.com/DanXi-Dev/DanXi/assets/58131351/d9e54367-25e5-451a-99f4-6a031108e174">

**系统信息**
 - 设备型号：
 - 系统版本：windows11
 - 旦夕版本（见「设置-关于本应用」）：1.4.2

**Comment by w568w** [comment]
cc @JingYiJun

**Comment by JingYiJun** [comment]
已解决
