### ISSUE TITLE
[BUG] 课评编辑器在英文下溢出，导致无法点击五星

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#361]
**复现步骤**
复现该 Bug 的步骤：
1. 切换旦夕语言为 English；
2. 到任何课程的课评编辑器页面；
3. 将第一行的 Overall Rating 选为五星；
4. 尝试在下面几行选择五星，无法选中。

**原因**
第一行的最后一列文字溢出，改变了单元格的宽度：

![xoCh8oUkqo](https://github.com/DanXi-Dev/DanXi/assets/8389787/057cd6f3-9677-420f-9194-fbbe72472ba2)

**Comment by HydrogenC** [comment]
I have no idea why the padding between stars become so large under mobile platforms.

**Comment by w568w** [comment]
@HydrogenC 问题在这里：

https://github.com/DanXi-Dev/DanXi/blob/6d0cb6d9caf837859cd91b6035697e4b132abebf/lib/page/danke/course_review_editor.dart#L429

指定列的宽度时，`1.fr` 代表「布局后，按此比例分配剩余空间」，`auto` 代表「总是尊重该子控件声称的 Intrinsic width」。

因此这样写，则显示评分项和说明的 `Text` 控件的宽度总是被尊重，而被设为 `1.fr` 的评分条，其内在宽度被无视，只能获得剩下的空间。**这显然和我们需要的相反**：`Text` 控件挤一点甚至截断都无所谓，评分条必须完整展示。

反转两者后即获得相对正常的挤压效果：

![图片](https://github.com/DanXi-Dev/DanXi/assets/8389787/30410f04-d8f2-478a-bf09-fe4e9cc611ed)
