### ISSUE TITLE
[Feature Request] WebVPN 代理支持

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#362]
**你想要什么样的功能？**
由于假期学生离校，需要接入 webvpn 代理以入校访问。

**如何实现？**
这不难实现，只需将请求的目标 URL 改为对应的 webvpn 版本即可。可以参考：

https://github.com/DanXi-Dev/DanXi-swift/blob/e5a2b542dc7a02f744f97b90d732740194161c36/Fudan%20Kit/Classroom/ClassroomAPI.swift#L57-L60

**Comment by ivanfei-1** [comment]
喜欢assign

**Comment by ppolariss** [comment]
图床也需加入webvpn功能

**Comment by w568w** [comment]
> 图片上传下载也需加入 webvpn 功能

自然是包括所有服务的。

**Comment by Limour-dev** [comment]
很久之前逆向的webvpn，不知道是否还有效：https://github.com/Limour-dev/daily_fudan_core/blob/main/FDU_WebVPN.py

**Comment by w568w** [comment]
从目前来看，webvpn 承载能力极其有限，开服时部分用户报告 webvpn 服务器直接无法访问。

@fsy2001 是否有必要急着加入 webvpn，还是继续使用 easyconnect？需要商榷。

**Comment by ivanfei-1** [comment]
> 从目前来看，webvpn 承载能力极其有限，开服时部分用户报告 webvpn 服务器直接无法访问。加入该功能后可能可用性不高。
> 
> @fsy2001 是否有必要急着加入 webvpn，还是继续使用 easyconnect？需要商榷。

否定的，我在所有的环境下使用内置的webvpn服务从基本未出现不稳定的情况，swift目前的做法是自动切换并且给用户添加手动开关按钮，可以在webvpn宕机时退回ec

**Comment by w568w** [comment]
> 建议待用户量稳定后做进一步的性能评估。

那么暂且从 1.4.4 计划中移除。

**Comment by ivanfei-1** [comment]
> > 从目前来看，webvpn 承载能力极其有限，开服时部分用户报告 webvpn 服务器直接无法访问。加入该功能后可能可用性不高。
> > @fsy2001 是否有必要急着加入 webvpn，还是继续使用 easyconnect？需要商榷。
> 
> 我认为 webvpn 不足以承载树洞的并发用户量，从 iOS 端的使用体验看，确实有很多用户报告 webvpn 有时无法使用。建议待用户量稳定后做进一步的性能评估。

最近几天我并没有见到有关webvpn出错的抱怨，“不足以承载并发数据量”缺乏有效的证据。

另一方面，假设有5%的用户（比如fsy2001自己）无法使用webvpn，我们不应为此牺牲另外95%的用户的方便性；另外，对于那5%，即使加了webvpn功能，他们也随时可以退回到ec

**Comment by w568w** [comment]
> WebVPN似乎不支持PUT方法。

那 Swift 端现在如何利用 WebVPN 访问论坛？我印象里还是有一些 PUT 方法的。

**Comment by w568w** [comment]
> 更新回复

这个还是比较重要的。

@JingYiJun 后端能否提供替代接口？例如 `PUT /floor <=> POST /floor/put`，后者直接调用前者的 handler。

**Comment by JingYiJun** [comment]
see OpenTreeHole/treehole_next#155

**Comment by JingYiJun** [comment]
后端已完成

**Comment by w568w** [comment]
目前，我们的登录逻辑是对于每个复旦站点登录一次，并从不缓存 Cookie。根据 @HydrogenC 的反馈，在登录 WebVPN 之后，再通过 WebVPN 重新登录其他复旦站点，可能会触发 UIS 的异地登录防护（因为自己将自己“顶号”了），导致无法正常继续使用 WebVPN。

为了解决这一点，需要首先解决 #426。

**Comment by HydrogenC** [comment]
> 目前，我们的登录逻辑是对于每个复旦站点登录一次，并从不缓存 Cookie。根据 @HydrogenC 的反馈，在登录 WebVPN 之后，再通过 WebVPN 重新登录其他复旦站点，可能会触发 UIS 的异地登录防护（因为自己将自己“顶号”了），导致无法正常继续使用 WebVPN。
> 
> 为了解决这一点，需要首先解决 #426。

Nonetheless, I believe that the problem is unrelated with this. I tried to comment out all login requests in the app so that only `WebVpnProxy` could make login requests to UIS. However, the problem still exists, the POST request to refresh the jwt token still fails always. I would propose to test with another Dart web client framework as another possible attempt to address the problem.

**Comment by w568w** [comment]
> I tried to comment out all login requests in the app so that only `WebVpnProxy` could make login requests to UIS. However, the problem still exists, the POST request to refresh the jwt token still fails always.

That sounds almost despairing. Anyway, I suggest you to:

1. Reproduce the problematic and correct request;
2. Compare their (a) HTTP Headers, (b) HTTP Payload and (c) HTTP Cookies one by one. If you are not sure, would you mind posting them here?

**Comment by HydrogenC** [comment]
> > I tried to comment out all login requests in the app so that only `WebVpnProxy` could make login requests to UIS. However, the problem still exists, the POST request to refresh the jwt token still fails always.
> 
> That sounds almost despairing. Anyway, I suggest you to:
> 
> 1. Reproduce the problematic and correct request;
> 2. Compare their (a) HTTP Headers, (b) HTTP Payload and (c) HTTP Cookies one by one. If you are not sure, would you mind posting them here?

Yeah I'm planning to try transferring the cookies obtained by `loginUIS` to another Http framework (and perhaps in another language) to test out the true cause.

**Comment by HydrogenC** [comment]
@w568w I'm working on a 三创 project lately and may not be able to inspect this in half a month. So maybe I should be de-assigned for now?

**Comment by w568w** [comment]
> @w568w I'm working on a 三创 project lately and may not be able to inspect this until half a month (appox.) later. So maybe I should be de-assigned for now?

Just do it.

**Comment by HydrogenC** [comment]
> > @w568w I'm working on a 三创 project lately and may not be able to inspect this until half a month (appox.) later. So maybe I should be de-assigned for now?
> 
> Just do it.

I'm working on it now since I've already figured out the exact problem and its solution, I could be assigned back.
