### ISSUE TITLE
[Feature Request] 茶楼UI微调

### ISSUE THREAD

**Issue by fsy2001** [DanXi-Dev/DanXi#365]
**你的功能需求和某个bug有关吗？**
否

**你想要什么样的功能？**
茶楼（原树洞）的UI需要微调，没有明确标准，和原来的UI能够明显区分即可。

**Comment by HydrogenC** [comment]
I will away from Shanghai in the next 3 weeks (no PC), so I'm afraid I cannot accomplish this recently.

**Comment by w568w** [comment]
目前来看近期尚无人手接手这一 issue。由于事情并不紧急，可从 1.4.4 中移除。

**Comment by HydrogenC** [comment]
Since I am stuck on #362, I will instead start to work on this issue these days.
