### ISSUE TITLE
[BUG] APP 名称与备案信息不符

### ISSUE THREAD

**Issue by KYLN24** [DanXi-Dev/DanXi#366]
**复现步骤**
复现该 Bug 的步骤：
1. 安装 app
2. 图标下方显示的 app 名不是“校园助手”

**系统信息**
 - 设备型号：与设备无关
 - 系统版本：与系统版本无关
 - 旦夕版本（见「设置-关于本应用」）：1.4.2

**Comment by w568w** [comment]
我提议改名为「校园助手」，但在 Android 端保留「旦夕」的 Activity 名，在 Windows 端保留「dan_xi」的窗口名。

**Comment by KYLN24** [comment]
从目前各种开会的讨论结果来看，这个方案暂时可以接受。开发者能预估完成更名的时间吗？以便和上下游其他项目的进度对齐。

**Comment by w568w** [comment]
Fixed in 32a6ec771d0332d63a226222297895092d891604.
