### ISSUE TITLE
[Feature Request] 课评支持按照课程代码或老师名搜索

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#375]
如题。

# 必要性
- 课程代码：当需要搜索某一学院或某一模块课程时，通常有相同前缀，可用课程代码快速搜索；
- 老师名：可搜索同一老师的不同课程，了解综合风评。

**Comment by HydrogenC** [comment]
Upstream: <https://github.com/OpenTreeHole/treehole_next/issues/126>

**Comment by HydrogenC** [comment]
While searching by course code is already implemented, searching by teacher name will be ready if <https://github.com/OpenTreeHole/backend/pull/142> is merged.
