### ISSUE TITLE
[BUG] 表情包没有从图片查看器中排除

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#384]
**复现步骤**
复现该 Bug 的步骤：
1. 进入任意既有图片、又有表情包图的帖子；
2. 点击图片，进入查看器；
3. 注意到标题中图片的数量计入了表情包图。左右滑动到表情包图的位置；
4. 显示图片无法加载的错误。

**预期结果**
表情包图从图片查看器中排除。

**Comment by ppolariss** [comment]
是否考虑在茶楼浏览时区分图片和表情包，现在表情包也会展示为 [图片] ，考虑替换成 [表情包]？
