### ISSUE TITLE
[Feature Request][Change] 修改课评学期信息

### ISSUE THREAD

**Issue by ppolariss** [DanXi-Dev/DanXi#386]
**你的功能需求和某个bug有关吗？**
`[否]`

**你想要什么样的功能？**
 为避免歧义，将2023学年-春季改为2023-2024学年 春季学期/暑假学期
现有代码中不区分暑假

**Comment by HydrogenC** [comment]
I indeed took this form of representation at first, but I found the string too long for a mobile device to display. Any solution for this?

**Comment by w568w** [comment]
> I found the string too long for a mobile device to display

Maybe just decrease the font size?
