### ISSUE TITLE
[BUG] 无法收到消息通知

### ISSUE THREAD

**Issue by ppolariss** [DanXi-Dev/DanXi#391]
**描述 Bug**
put message/id方法错误，应该是delete？
https://github.com/DanXi-Dev/DanXi/blob/429ac3a393be50353d29140e5872a7f23ca83fbc/lib/widget/forum/forum_widgets.dart#L925

**复现步骤**
复现该 Bug 的步骤：
1. 发帖
2. 有人回复你

**系统信息**
 - 设备型号：
 - 系统版本：
 - 旦夕版本（见「设置-关于本应用」）：1.4.4

**Comment by cryindevil** [comment]
不清楚 issue标题 _无法收到消息通知_ 和bug描述中指出的 _markMessageAsRead函数_ 之间的关联性是什么？

**Comment by ppolariss** [comment]
> 不清楚 issue标题 _无法收到消息通知_ 和bug描述中指出的 _markMessageAsRead函数_ 之间的关联性是什么？

现在看来似乎没有联系，markMessageAsRead的bug并不会影响消息通知。目前版本可以正常收到通知
