### ISSUE TITLE
[Feature Request] 支持Markdown高亮格式

### ISSUE THREAD

**Issue by kooWZ** [DanXi-Dev/DanXi#395]
**你的功能需求和某个bug有关吗？**
`[否]`

**你想要什么样的功能？**
在https://github.com/singularity-s0/flutter_markdown_selectable/pull/1 中添加了对`<mark>` tag的支持，能够inline实现背景黄色高亮。
因此可以考虑在Markdown编辑器中支持`==text==`或者`<mark>text</mark>`的高亮语法。
问题：
1. 有没有必要：不是标准markdown格式，并且论坛已经支持粗体，高亮可能影响观感
2. 当前audit #394 也使用高亮 ，如果在帖子中引入高亮可能会导致audit页面混淆，需要audit改成红色文字显示

**Comment by w568w** [comment]
我觉得没有特别的必要。除了你所说的原因以外， $\LaTeX$ 也是支持行间高亮元素的。
