### ISSUE TITLE
[BUG] 手机无法点开致谢同学的主页

### ISSUE THREAD

**Issue by ppolariss** [DanXi-Dev/DanXi#422]
**描述 Bug**

**复现步骤**
复现该 Bug 的步骤：
1. 设置-关于本应用-致谢
2. 点击任意同学名字
4. 无反应

**截图**
如果方便的话，你可以添加截图。

**系统信息**
 - 设备型号：
 - 系统版本：
 - 旦挞校园助手版本（见「设置-关于本应用」）：1.4.4

**Comment by HydrogenC** [comment]
I cannot reproduce this through, is it related to Android settings about link behavior?
