### ISSUE TITLE
[Feature Request]  一卡通或许可以支持充值功能？

### ISSUE THREAD

**Issue by Oneton429** [DanXi-Dev/DanXi#428]
**你的功能需求和某个bug有关吗？**
否

**你想要什么样的功能？**

一卡通或许可以支持多平台充值功能？

众所周知，一卡通可以在eCard微信小程序用微信支付充值  

但是不众所周知的是，也可以在[eCard网站](https://ecard.fudan.edu.cn/epay/)上发起到[支付平台](https://payment.fudan.edu.cn/pay/index.html)进行支付，在这里可以选择微信或支付宝或银联支付

对于想把所有支付迁移到支付宝平台的人（比如我，总之张小龙**motherless**）来说，算是解决了一个大忙（这下微信支付月支出终于能到两位数了）

而且，使用支付宝，冲eCard还可以像实体店购物一样，使用红包和百次立减，虽不多但也至少相当于打9996折充值（假设每天充50的话），还能养芝麻信用和支付宝会员等级，~如果通过信用卡支付的话还能养征信?(可以用还信用卡把微信的钱提现)~

支付平台会生成一个二维码，这个码微信支付宝都能扫，是一个http url，支付宝查了[可以用扫一扫打开任意链接](https://zhuanlan.zhihu.com/p/644100287)，微信没查（不过真有人会在这里用微信充么），手机端银联网站会打开云闪付

不过涉及金钱方面的，可能就需要担心大家的信任程度了（~比如会不会把充值码替换成开发者的eCard充值码这种的~）

**Comment by w568w** [comment]
不好意思，忘记回复了。

技术上这个功能是可行的，至少能推进到提交支付平台缴费项。然而有两个问题：

1. 像这类支付平台的接口可能是高度动态的，不能保证稳定性。会增加后期的项目维护成本（当然，学校内的其他接口也存在不稳定，但相较来说，第三方接口的可靠性更低一些）；
2. 学校出于安全考虑，不会允许第三方工具实现支付相关功能，这本质上和侵入计算机系统差不多：由于旦挞不会闭源，向社会开放此类接口的访问实现有安全风险；
3. 涉及到财产安全的功能不仅仅是“用户信不信任开发者不主动作恶”的问题，还有“由于有意或无意的代码错误造成财产损失，谁来负责”的问题。如果要做，必然要得到用户的责任豁免知情同意，我想部分用户是不愿意承担这个风险的。

如果有其他问题，请 Reopen。
