### ISSUE TITLE
[BUG] renderText 在渲染包含引用的内容时会保留层号

### ISSUE THREAD

**Issue by 123789456ye** [DanXi-Dev/DanXi#438]
**复现步骤**
复现该 Bug 的步骤：
- Android 稳定复现

**系统信息**
 - 设备型号：
 - 系统版本：Android 14
 - 旦挞校园助手版本（见「设置-关于本应用」）：测试版本（11.19）

**Comment by w568w** [comment]
@AInfinity-LilacDream 考虑看一下？我想相关代码应当在这附近：

https://github.com/DanXi-Dev/DanXi/blob/03cd66ce127d9483c4e775fbc072807f30437963/lib/widget/forum/forum_widgets.dart#L235-L241

**Comment by w568w** [comment]
根据 @ppolariss 的反馈，该问题广泛出现在所有调用 `renderText` 的地方，应当首先检查该方法的问题。

**Comment by AInfinity-LilacDream** [comment]
好的。我会抽空尝试修复这个bug



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月20日(周三) 中午11:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DanXi-Dev/DanXi] [BUG]  若回复中有引用，在最新楼层预览中会先看到引用的层号 (Issue #438)




 
@AInfinity-LilacDream 考虑看一下？我想相关代码应当在这附近：
 
https://github.com/DanXi-Dev/DanXi/blob/03cd66ce127d9483c4e775fbc072807f30437963/lib/widget/forum/forum_widgets.dart#L235-L241

**Comment by w568w** [comment]
由于 @AInfinity-LilacDream 迟迟不响应，且未能复现此问题，暂时从 1.4.5 Milestone 中移除。

**Comment by w568w** [comment]
我会研究这一问题。

**Comment by w568w** [comment]
看起来是由 11e52adc271aac60b806c689160c81e01d6d9ff1 引入的 bug。该提交将 mention 等的 HTML Tag 名称由 `hole_mention` 改为了 `holeMention`，使得 renderText 中的正则匹配失效。

cc @HydrogenC
