### ISSUE TITLE
[Feature Request] 只看此人功能

### ISSUE THREAD

**Issue by ppolariss** [DanXi-Dev/DanXi#443]
**你的功能需求和某个bug有关吗？**
`[否]`

**你想要什么样的功能？**
对齐swift
可以在帖子下任一层楼选择 只看此人 或 查看对话
选择 只看此人 时，筛选当前帖子中层主发的全部内容
选择 查看对话 时，若选择的楼层包含引用，递归筛选当前层和被引用的层，若不包含引用，按钮为灰色无法选中

**Comment by w568w** [comment]
查看对话 和 #441 重复。
