### ISSUE TITLE
[Feature Request] 接入表情包第二弹

### ISSUE THREAD

**Issue by KYLN24** [DanXi-Dev/DanXi#445]
**你的功能需求和某个bug有关吗？**
`[否]`

**你想要什么样的功能？**
接入旦挞猫猫表情包第二弹

**Comment by KYLN24** [comment]
如果方便的话，最好能设计一个云控方案

**Comment by w568w** [comment]
> 如果方便的话，最好能设计一个云控方案

这是另一个 issue，请单独提交。
