### ISSUE TITLE
[Feature Request] 为 toml 静态信息加入开发组公告功能

### ISSUE THREAD

**Issue by KYLN24** [DanXi-Dev/DanXi#452]
**你的功能需求和某个bug有关吗？**
`[是]`

**你想要什么样的功能？**
#390 适配了 toml 格式静态信息文件，但没有约定开发组公告的实现形式。

**Comment by KYLN24** [comment]
这个功能还需要吗？

**Comment by kooWZ** [comment]
@w568w 字段格式没有问题。

小驼峰是直接抄了json文件的字段名，没有考虑到toml文件的命名风格，滑跪

**Comment by kooWZ** [comment]
P.S. 由于之前存在的bug，#461 merge之前开发组公告功能会报错，所以似乎也不需要考虑1.4.5的兼容性。如果需要改`updatedAt`字段名，可以现在改

**Comment by w568w** [comment]
> 如果需要改`updatedAt`字段名，可以现在改

可以之后再改一下，看到这句话的时候已经 merge 了，抱歉。
