### ISSUE TITLE
[BUG] 一旦 UIS 登录流程抛出异常，WebVPN 将再也无法使用

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#455]
**描述 Bug**
`loginWebvpn` 方法没有捕获任何来自 `UISLoginTool.loginUIS` 的异常：

https://github.com/DanXi-Dev/DanXi/blob/4226b4a6a8c57c956872e1607bbf4be16ad8870a/lib/util/webvpn_proxy.dart#L123-L129

因此，一旦 `UISLoginTool.loginUIS` 抛出异常，在 `await` 时就会因抛出同步异常而中断函数，后续的 `loginSession = null;` 永远不可能被执行，故将导致 WebVPN Proxy 卡死在错误状态中，无论如何发送新请求都不会恢复。

cc @HydrogenC

**Comment by HydrogenC** [comment]
Will a simple `try...catch` clause work with capturing concurrent errors? Or I should use `.then()` or `.onError()` instead?

**Comment by w568w** [comment]
> Will a simple `try...catch` clause work with capturing concurrent errors? Or I should use `.then()` or `.onError()` instead?

You cannot `try catch` a `somethingThrowErrorAsync()`, but `await somethingThrowErrorAsync()` turns an async exception into a sync one, thus it can be caught.

Please read [this](https://dart.dev/libraries/async/futures-error-handling#potential-problem-failing-to-register-error-handlers-early) about the caveats.
