### ISSUE TITLE
[BUG] Unable to load Forum

### ISSUE THREAD

**Issue by JinnyWong** [DanXi-Dev/DanXi#469]
**Bug:** Unable to load the Forum tab. 
- Error message: "The data couldn't be read because it isn't in the correct format."
- Not a network issue, I've tried with WiFi and mobile data.
- Other tabs work fine.

<br>

**复现步骤**
1. Start the app and click on the Forum tab.

<br>

**截图**

<img src="https://github.com/user-attachments/assets/29696e14-dceb-422a-acb1-43aada8f82e8" alt="Error Screenshot" width="300" height="500">

<br>

**系统信息**
 - 设备型号：iPhone 11 Pro Max 
 - 系统版本：iOS 17.5.1
 - 旦挞校园助手版本（见「设置-关于本应用」）：Danta version 2.2.0 (627)

**Comment by w568w** [comment]
Because we are temporarily maintaining the service. Check it again now!
