### ISSUE TITLE
[Bug] Tapping on a BBS Post will cause the view to scroll up

### ISSUE THREAD

**Issue by kavinzhao** [DanXi-Dev/DanXi#58]
Under certain conditions (probably when the scrollbar is close to the bottom of the screen), opening a BBS Detail page will cause the view of the previous page to scroll up.

This issue needs more investigation.

@w568w Please confirm if this is reproducible on Android

**Comment by w568w** [comment]
Nop. Is it caused by the loss of state?

**Comment by kavinzhao** [comment]
Might be related to new contents' being loaded
