### ISSUE TITLE
[BUG] 帖子里的URL解析异常

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#61]
如题。 HTML 中的标签都被解析成链接的一部分了（`http://www.baidu.com/</a></p><p>`），导致没法正常点进链接。  
  
BTW，不要直接把 Html 喂给 Linkify ，必要时应该使得 HTML Widget 中的 Text 全部替换为 Linkify。

**Comment by kavinzhao** [comment]
Fixed with 4c7f15d
