### ISSUE TITLE
[BUG] post detail页面中，如果遇到超长帖子，用户滑动到底部时会直接反弹会顶部

### ISSUE THREAD

**Issue by kavinzhao** [DanXi-Dev/DanXi#63]
考虑限制一下反弹速率

**Comment by kavinzhao** [comment]
事实上回弹不应该弹过页面底部。即使速度非常大，那么反弹后的scroll position也应停留在页面底部。

**Comment by kavinzhao** [comment]
可以试试[这个](https://stackoverflow.com/questions/51536756/flutter-listview-jumps-to-top/62462777#62462777)

**Comment by kavinzhao** [comment]
Should be fixed in recent commits. Watching

**Comment by w568w** [comment]
Have it got fixed?

**Comment by kavinzhao** [comment]
> Have it got fixed?

I would say it's "workarounded" rather than fixed. Currently we are limiting the length of image to prevent this issue from being produced, but the underlying problem is still there, and there's not much we can do about it.

**Comment by kavinzhao** [comment]
Since this issue has been workarounded and its occurrence is very low, I'm going to close this issue.
