### ISSUE TITLE
[Feature Request] 树洞支持翻页到底部

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#66]
用户报告在浏览较长帖子时遇到了困难，他们通常需要翻页很久才能找到最新回复。

我们应当在浏览页面添加一键滑到底部的功能。或者至少，在帖子列表页面点击最新回复时，应该直接进入帖子并滑到底部，而不是打开编辑器页面。

**Comment by kavinzhao** [comment]
可以加入论坛式翻页功能

**Comment by kavinzhao** [comment]
已支持
