### ISSUE TITLE
[BUG] 平安复旦和教务处通知不能自动登录

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#74]
部分用户依然报告他们的[平安复旦不会自动登录](https://www.fduhole.tk/#/discussion/3159)。

此外，我也注意到有时教务处通知也仍然不会自动登录。

这一问题需要进一步彻查。

**Comment by w568w** [comment]
今天再也无法复现`教务处通知也仍然不会自动登录`的Bug了。相当奇怪。

**Comment by kavinzhao** [comment]
可以在WebView上进行一些操作，检测到URL是UIS的话就自动填写提交

**Comment by singularity-s0** [comment]
作为一个fallback或者workaround，可以在我们的InAppBrowser里面用JavaScript实现手动登录
