### ISSUE TITLE
[BUG] 自由复制不能跨段复制

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#76]
自由复制的功能是由 Markdown 控件支持的，可能得等待上游解决这个问题。

**Comment by w568w** [comment]
上游问题链接：https://github.com/flutter/flutter/issues/99819。

**Comment by singularity-s0** [comment]
There is actually a simple fix for this:

1. Wrap everything you expect to be selectable in `SelectableArea`
2. Override `MarkdownBody`, it uses `SelectableText.rich` to implement selection but it really should use `Text.rich` instead. `Text.rich`(and also `Text`) extends `Selectable`, which automatically looks for a ancestor `SelectableArea` and joins the group.

**Comment by singularity-s0** [comment]
I have created a modified `flutter_markdown` package that does the job. Please try https://github.com/singularity-s0/flutter_markdown_selectable when you have time. Remember to wrap the entire renderer in `SelectableArea`.

**Comment by w568w** [comment]
Oops, a mindless click.
