### ISSUE TITLE
[Feature Request] Accessibility Coloring

### ISSUE THREAD

**Issue by kavinzhao** [DanXi-Dev/DanXi#77]
Some users have requested accessibility features(optimize empty classroom page for color blind) be added to the app.

Color-blind vision can be simulated on an Android with Developer Settings on.

**Comment by w568w** [comment]
Also, the app could be equipped with [Accessibility Content Description ](https://developer.android.google.cn/codelabs/starting-android-accessibility?hl=en#5) for visually impaired users with a screen reader. 

(Flutter has done a lot for us on Android already, but we should test it on iOS too.)
