### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KYLN24** [DanXi-Dev/DanXi#84]
**Describe the bug**
课表不刷新

**To Reproduce**
选了课
回到旦夕
在课表页面刷新，没有显示新的课
http log 中没有产生新的请求

**Expected behavior**
重新获取课表

**Screenshots**
无

**Smartphone (please complete the following information):**
 - Device: 华为
 - OS: 鸿蒙2
 - Browser 自带浏览器
 - Version 54

**Additional context**

**Comment by kavinzhao** [comment]
Already fixed in 1.2.5, closing.
