### ISSUE TITLE
[Feature Request] 支持查询研究生课表

### ISSUE THREAD

**Issue by KYLN24** [DanXi-Dev/DanXi#85]
**你的功能需求和某个bug有关吗？**
`[是/否]`否

**你想要什么样的功能？**
支持查询研究生课表
yjsxk.fudan.edu.cn

**Comment by kavinzhao** [comment]
在没有研究生账号的情况下无法开发

**Comment by w568w** [comment]
Feature 已经由 @Frankstein73 基本上完成了。
