### ISSUE TITLE
[Feature Request]上架各大安卓应用商店

### ISSUE THREAD

**Issue by JingYiJun** [DanXi-Dev/DanXi#88]
**你的功能需求和某个bug有关吗？**
`[是/否]`否

**你想要什么样的功能？**
上架各大安卓应用商店，比如小米应用商店。

**Comment by kavinzhao** [comment]
cc @w568w

**Comment by w568w** [comment]
根据《小米应用商店个人开发者升级公告》：

> 尊敬的开发者： 您好！ 为保障用户的数据及个人信息安全，加强用户隐私保护能力。**小米应用商店即日起暂停收录个人开发者账号发布的APP**，针对已在架APP，需在6月30日前，完成开发者身份类型的变更（个人开发者转企业开发者）。6月30日后，对个人开发者旗下的应用，将依照《应用发布协议》采取相关措施。 
>《应用发布协议》：https://dev.mi.com/console/doc/detail?pId=858 
> 开发者身份变更操作方法：https://dev.mi.com/distribute/doc/details?pId=1068 
> 如果有任何问题，可联系：developer@xiaomi.com

其他应用商店也有类似政策。**总之，目前所有国内应用商店都不欢迎、或者禁止个人开发者上架应用**。除非国家放宽政策，否则我们无能为力。
