### ISSUE TITLE
[Feature Request]个性主题与动画、系统功能

### ISSUE THREAD

**Issue by JingYiJun** [DanXi-Dev/DanXi#89]
**你的功能需求和某个bug有关吗？**
`[是/否]`否

**你想要什么样的功能？**
~~1、修改底部导航栏的布局，比如修改顺序，把首页放到中间，或者如果不喜欢树洞的可以把树洞去掉。~~
~~2、字体可以根据系统的个性化字体来调整（针对安卓系统），比如我用的小米阡陌行书字体，在其他APP可以自动应用字体，但是在旦夕里不行；或者开发旦夕自己的字体修改选项，包括大小、粗细等。~~
- [x] 3、背景的主题色不要一直是一种颜色好不好，可以更换成自己喜欢的颜色或者图片。
- [ ] 4、深色模式可以增加选项（1）深色（2）浅色（3）跟随系统主题
- [x] 5、主页可以直接左右滑动来调整栏目，不必点击底部导航栏。
- [x] 6、手动、自动检查更新，wifi下自动更新等。
~~7、GPS定位来确定校区，不必手动更换。~~

**Comment by kavinzhao** [comment]
3, 4, 5 WIP
2, 6 cc @w568w 
1.导航栏一共就4个项目，在屏幕可以容纳的前提下似乎没有必要支持动态调整
7.用户一般只需设置一次校区，不必经常更换，手动设置应该问题不大。加之定位权限属于敏感权限，应尽量避免请求。

**欢迎反驳**

**Comment by w568w** [comment]
关于第 2 点：目前 Flutter 框架使用的默认字体是 [Roboto](https://fonts.google.com/specimen/Roboto)。根据[官方说明](https://github.com/flutter/flutter/issues/48381)，目前还没有好的方案使得 Flutter 适配系统字体。如果要实现这一点，只能等待框架自身更新。**除非把整个旦夕推倒重来，否则暂时没有其他解决方案。**

关于第 6 点：Work In Progress

**Comment by w568w** [comment]
深色模式可以通过直接切换系统的深色模式进行，因此目前我们没有发现这一功能的必要性。

如果你认为该功能仍是有必要的，可以重新开放此 issue。目前，绝大部分工作都已完成。
