### ISSUE TITLE
[BUG] iOS Dark/Light Theme Transition 

### ISSUE THREAD

**Issue by singularity-s0** [DanXi-Dev/DanXi#96]
Due to the unreasonable implementation of Flutter's Cupertino Theme system (they use `CupertinoDynamicColor` instead of dark/light theme), currently transitioning between Dark and Light theme require a full rebuild of the app.

Currently, the problem lies in that Material Widgets do not respect platform brightness as Cupertino widgets do (what's the difference?). They only respect `Theme.of(context)`, which isn't dynamically updated in `CupertinoApp` as in `MaterialApp`. We should either rewrite/replace all Material Widgets, or switch to an alternate theme system.

This issue slightly impacts user experience, and needs to be fixed when there is time.

**Comment by w568w** [comment]
It doesn't seem like a bug to me - Material widgets needs a rebuild sometimes too.

**Comment by singularity-s0** [comment]
check the two branches referenced above for some latest efforts into this issue
